### ISSUE TITLE
 I cannot login to admin if the admin folder/url contain uppercase letters.

### ISSUE THREAD

**Issue by Havouza** [thirtybees/thirtybees#199] opened 2017-04-25 18:22 UTC
Subject say it. If the adminfolder/url contains uppercase letters, you cant login

Like

/index.php?controller=AdminLogin&token=f041618e6c8126e8bdeeb9924cf6c734&redirect=**PiwikAnalytics**

**Comment by Havouza** [comment] 2017-04-27 06:34
When the url look like this
https://www.beautyandpleasure.co.uk/admin46336vcsa/index.php?controller=AdminLogin&token=f041618e6c8126e8bdeeb9924cf6c734&redirect=AdminDashboard

it throws me to log in.

If I change the url to this 
https://www.beautyandpleasure.co.uk/admin46336vcsa/index.php?controller=AdminDashboard

It goes there without a problem

**Comment by firstred** [comment] 2017-06-28 05:09
I believe we figured out via the forum that this was correct behavior. Is that correct?

**Comment by yaniv14** [comment] 2017-06-30 12:39
I can confirm that installing TB on windows with wamp server on a folder with uppercase letters (MyShop) causes many weird issues, when one of them is accessing the back office.
I also mentioned it in the forum: https://forum.thirtybees.com/topic/119/thirtybees-folder-url/4

**Comment by firstred** [comment] 2017-08-30 11:32
What is the wamp software? Xampp?

**Comment by yaniv14** [comment] 2017-10-06 05:55
Similar to Xampp.

http://www.wampserver.com/en/

**Comment by firstred** [comment] 2017-12-01 04:06
Don't have the tools atm :(

**Comment by Traumflug** [comment] 2019-04-04 22:06
Hmm. Original issue solved. Second issue is "many weird issues" with a installation on WAMP when installing into a folder with uppercase letters.

While XAMPP and WAMP aren't supported (patches nevertheless welcome) we'd at least need "many weird issues" reports, one issues by another. Closing, because here's nothing to do.

**Closed by Traumflug** 2019-04-04 22:06 UTC
Labels: Bug, Estimate: S, Needs more info, Priority: high
