### ISSUE TITLE
PHP translation BUG (maybe?)

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#251] opened 2017-05-31 11:23 UTC
Again, I am not sure if to consider it as a bug.
But when you have a space after opening and before closing parentheses, the string won't be recognized as translatable string:

$this->l('Cart block') - will work

But this won't:
$this->l( 'Cart block' )

**Comment by Traumflug** [comment] 2017-05-31 11:47
Unless there's some black magic going on, `l()` is a normal function: https://github.com/thirtybees/thirtybees/blob/1.0.x/classes/controller/AdminController.php#L456

**Comment by firstred** [comment] 2017-05-31 13:20
Nope, it is just how the language mechanism finds the strings. The .tpl and .php files are being regexed to find the strings.

Therefore it's better to stick to thirty bees' coding standards: https://github.com/thirtybees/thirtybees/blob/1.0.x/CONTRIBUTING.md#coding-standards
it avoids trouble like this. In the future (1.1) we might use the Nikic PHP parser to improve it.

**Comment by roband** [comment] 2017-06-02 07:42
As an interim fix perhaps the regexp can be tweaked a bit to avoid silly cases like yaniv14 reported?

**Comment by firstred** [comment] 2017-06-13 03:14
Maybe. The logic can be found over here: https://github.com/thirtybees/thirtybees/blob/c38782bb27086b826ca888c4490463c67dbd9abe/controllers/admin/AdminTranslationsController.php#L1795

**Comment by Traumflug** [comment] 2019-04-04 21:58
@yaniv14, would you be kind enough to tell us how one can see or how you found this bug? A fix probably wouldn't be that hard, but we'd need a way to test and prove it.

**Comment by yaniv14** [comment] 2019-04-05 08:46
@Traumflug I bumped into this so called bug 2 years ago.
It happen when I realized that I am missing translation in back office.
PhpStorm was configured on php code style to add a space inside parentheses before and after quotes, which leads to $this->l( "Cart block" ). in this case the translation controller won't find this string as translatable and won't show it in back office -> localization -> translations.

**Comment by mke-tb** [comment] 2019-08-25 16:48
Still reproducible on 1.1.0. All you need to do is to modify any translation defined like `$this->l('string')` as `$this->l( 'string')` or `$this->l('string' )` and you won't be able to see it anymore on `Localization  -> Translations  -> Modify translations`.

We can update the regex on `AdminTranslationsController->userParseFile` to allow one space after the opening parenthese and one before (and probably not more). I was unable to find any rule regarding to this under [Symfony Standards](http://symfony.com/doc/current/contributing/code/standards.html) (which we claim that we follow) so I think we can allow both cases (no spaces around parentheses and one space max after opening/before closing).

Or we say that we don't support it and just close this issue.

**Comment by Traumflug** [comment] 2019-08-25 17:11
It's probably a matter of performance whether `\s` or `\s*` gets inserted, and how many of them, to support more/all valid PHP code. As one can see above, non-thirty-bees code gets parsed as well, so being flexible when reading/parsing, being strict when writing appears to be a good rule of thumb.

**Comment by mke-tb** [comment] 2019-08-25 17:33
Performance risk seems to be a good point, is there a way to measure the impact? This is a method that runs for each file so we need to make sure that it won't slow down the system.

We should also need to well define flexibility in this context. Supporting as much cases as possible or only the most preferred ones?

**Comment by Traumflug** [comment] 2019-08-25 21:17
Ideally supporting as much as possible. More sophisticated parsing doesn't put any extra work onto users, so they can only win (by seeing their not-so-standard code getting parsed).

Performance measurement is simple: load one of the translation pages and look at how long it takes. Five times, to get an average. Then implement code to allow spaces and do the same again. If the latter takes half a second longer, performance doesn't matter. If it takes 20 seconds extra, it does.

General shop operations should be without impact in either case. Reading translations is a simple `include()` of one of the files in _translations/_.

**Comment by Traumflug** [comment] 2019-08-27 12:36
939392bc001e13c132b4ecca25f3afc39f27bc71 looks good ... but is just 10%, isn't it? All the other patterns certainly want to allow spaces around `(` and `)` as well :-)

**Comment by mke-tb** [comment] 2019-08-27 20:02
> [939392b](https://github.com/thirtybees/thirtybees/commit/939392bc001e13c132b4ecca25f3afc39f27bc71) looks good ... but is just 10%, isn't it? All the other patterns certainly want to allow spaces around `(` and `)` as well :-)

Well it's a start... Only `php` or all?

**Comment by Traumflug** [comment] 2019-08-28 15:03
Wherever is makes sense, please.

**Comment by Traumflug** [comment] 2019-08-30 19:17
Aaah, second commit is much better, thank you. Allowed myself to add another tidbit, other than that it should be fine. I see no noticeable performance distinction.

Moved directly to _1.1.x_.

**Closed by Traumflug** 2019-08-30 19:17 UTC
Labels: Bug, Estimate: L, Priority: low
