### ISSUE TITLE
Tags get shortened on CSV import

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#262] opened 2017-06-23 10:04 UTC
See https://forum.thirtybees.com/topic/432/is-there-a-tag-field-limit-in-thirty-bees

Apparently, CSV import applies the 32 character limit to all tags together, instead of each individual tag. Adding longer tags manually works fine.

**Comment by alwayspaws** [comment] 2017-06-23 12:45
Thanks for opening this issue. I do everything via CSV.

**Comment by firstred** [comment] 2017-06-23 14:14
Good to know that you can manually input them. That means at least the database can hold them :)

**Comment by alwayspaws** [comment] 2017-06-23 14:40
Yes, that's a plus. :)

**Comment by firstred** [comment] 2017-06-28 03:44
Hmmz, I'm unable to reproduce this.

It is indeed true that tags get trimmed to 32 characters max, but you should be able to import as many tags as you like.

Make sure you use this format `"tag one, tag two, etc."`

**Comment by alwayspaws** [comment] 2017-07-03 22:15
Updated info is in the forum thanks to firstred and traumflug.

**Comment by firstred** [comment] 2017-07-03 23:17
Indeed, let's close this.

**Closed by firstred** 2017-07-03 23:17 UTC
Labels: Bug, Estimate: M, Needs more info, Priority: critical
