### ISSUE TITLE
Fields of Merchandise Returns

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#1190] opened 2020-05-10 15:33 UTC
The return statuses fill all fields with strong color and difficult to see the “ID”, “Order ID” and “Date issued”. 
![image](https://user-images.githubusercontent.com/38436949/81507687-f0ee9880-92f6-11ea-912b-9bfbbfd079d9.png)

I think it’s better use the same font color on “ID”, “Order ID” and “Date issued” as it is used on “Status”.
![image](https://user-images.githubusercontent.com/38436949/81507693-f815a680-92f6-11ea-9229-8fdeba7bcec4.png)
Also is good idea use dropdown to choose the status.

**Comment by getdatakick** [comment] 2020-09-25 09:47
already fixed, duplicate of issue #1246

**Closed by getdatakick** 2020-09-25 09:47 UTC
Labels: Duplicate
