### ISSUE TITLE
'Attach invoice pdf to email' option not respected

### ISSUE THREAD

**Issue by NaturePinks** [thirtybees/thirtybees#1155] opened 2020-03-16 08:32 UTC
TB 1.1.0
Niara theme

Email sent to customer has invoice pdf attached even if Order Status is set not to send pdf invoice.

Forum topic: https://forum.thirtybees.com/topic/3792-possible-bug-order-status-attach-invoice-pdf-option-is-not-respected/

![order-processing](https://user-images.githubusercontent.com/40917366/76737178-55292c00-678e-11ea-8ecd-213ca4d110b6.png)

**Comment by getdatakick** [comment] 2020-03-16 10:22
Closing as not a bug. You probably have some override installed that causes this issue. Try to disable all overrides

**Closed by getdatakick** 2020-03-16 10:22 UTC
Labels: Could not reproduce
