### ISSUE TITLE
PayPal Module not working properly

### ISSUE THREAD

**Issue by Vegaanders** [thirtybees/ThirtyBees#163] opened 2017-03-30 11:24 UTC
PayPal native module

1. All 3 alternatives point at PayPal Express Checkout. 

2. Paypal Express Checkout button allow you to go to Paypal without ticking the Agree to ToS box

**Comment by firstred** [comment] 2017-03-30 11:33
And what is so "not working properly" about this?

**Comment by Vegaanders** [comment] 2017-03-30 11:48
You should not be able to pay without agreed to the ToS. That you have to do with Webpay Standard. Should also be when you want to use Express Checkout. These two payments are different, otherwise they would not excist. I have a feeling that the Standard should not link to the express checkout as the link shows

**Comment by Vegaanders** [comment] 2017-03-30 11:50
Unfortunately, Stripe is not an alternative in Europe when they keep your money for 7 days before payout

**Comment by firstred** [comment] 2017-03-30 11:51
PayPal has merged the payment flows.

The normal PayPal checkout button should not be visible if you haven't checked the ToS. That might be a problem with your checkout.

The PayPal Express Checkout document states that you click the button first and after you have authorized the payment with PayPal, to show the ToS on your review page (step 4): https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/checkout-flow/

**Comment by Vegaanders** [comment] 2017-03-30 11:53
And if you use one page checkout?

**Comment by firstred** [comment] 2017-03-30 11:54
Still applies.

**Comment by Vegaanders** [comment] 2017-03-30 12:02
PS works like if you have no account you must fill in the address form before you see the payment alternatives. This is no good business manner, and the customer wants to know what alternatives they have before they give away some info. In our line of business, guest checkout is important and used by almost 80%, even if I have realized that there is no real difference, in reality only a password. 
Therefore I show the payment alternatives when you come to the OPC so the customer knows the alternatives. I can't see why not

**Comment by firstred** [comment] 2017-03-30 12:04
That's your choice and not what the payment gateway has designed.

**Closed by firstred** 2017-03-30 12:04 UTC

**Comment by Vegaanders** [comment] 2017-03-30 12:06
OK. But still I am convinced that the two different payment ways should end up on the same paypal page. Or that is said so in the developer site. Because if so, The express checkout has absolutely no value what so ever

**Comment by Vegaanders** [comment] 2017-03-30 12:07
NOT end up

**Comment by firstred** [comment] 2017-03-30 12:11
Then I suggest your read some more about the checkout flows, because the express checkout button certainly adds some value to your checkout process.
