### ISSUE TITLE
Supply order reference problem

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1035] opened 2019-09-03 15:21 UTC
Since the version 1.1.0 there seems to be a bug when saving supply orders. Once the order is created and resaved the product reference is messed up.

I have created a video: https://streamable.com/1tblu

I believe that this issue was introduced with https://github.com/thirtybees/thirtybees/commit/eb847cd1d0980c839230eb7d0a05dc9b19b29c18#diff-bbf3bc3c8540ec292f3107d0e6f92080 As I tested it with 1.1.0 and only changed this file. Then it works as expeced.

**Comment by getdatakick** [comment] 2019-09-03 15:46
this commit is not part of 1.1.0 release. Is the bug in 1.1.0, or in bleeding edge?

**Comment by eschiendorfer** [comment] 2019-09-03 15:48
Oh damn. Sorry for that! The issue comes already with 1.1.0.

**Comment by eschiendorfer** [comment] 2019-09-03 15:51
Actually to be honest. With 1.1.0 I even get more problems when saving. Things like: 
```
Feld: price_te erforderlich
Feld: discount_rate erforderlich
Feld: discount_value_te erforderlich
Feld: price_with_discount_te erforderlich
Feld: tax_rate erforderlich
Feld: tax_value erforderlich
Feld: price_ti erforderlich
Feld: tax_value_with_order_discount erforderlich
Feld: price_with_order_discount_te erforderlich
```

**Comment by getdatakick** [comment] 2019-09-03 16:03
That was fixed in issue #1013

**Comment by eschiendorfer** [comment] 2019-09-03 16:05
Is it possible for you to reproduce it?

**Comment by getdatakick** [comment] 2019-09-03 16:06
Anyway, I'd bet that this issue was injected by commit 078765ff2c1f8f81501b076890f353efb60e79d8. Didn't test, though

**Comment by eschiendorfer** [comment] 2019-09-03 16:15
Ok I tested it a bit now. You are right! When I delete this `public function validateController($htmlentities = true)` then I get the same problems as in bleeding edge.

**Comment by getdatakick** [comment] 2019-09-03 16:26
Well, the current version of SupplyOrderDetail file looks ok to me. 

I think that there is something wrong with the associated controller -- it probably provide or pass non-standard data down to the object model. That's probably the reason why this object model implemented its own `validateController`

**Comment by getdatakick** [comment] 2019-11-15 13:33
The root cause of this problem is in the `ObjectModel::validateController()`. This method not only validates input values, but also **copies** data from request to current object properties.

This means that we should call this method only for **primary object** associated with controller, in this case `SupplyOrder`. We should not call it for `SupplyOrderDetail` detail entries created by this controller, because that results in storing SupplyOrder data inside SupplyOrderDetail entries.

Originally, the method `validateController` was overwritten in `SupplyOrderDetail` in order to avoid this data copying problem. 

This override was removed in commit 078765f, and that introduced this issue.

It's not necessary to restore this override, becase most of the validation it implemented is also performed during the object model `save()` call.

The only things that are not checked when the object is saved are upper/lower are limits for `quantity_expected`, `tax_rate`, and `discount_rate` fields.

The fix is therefore simple: remove call to `validateController` for detail entries, and add custom validation for these three fieldss

**Comment by eschiendorfer** [comment] 2020-01-14 16:19
This problem seems to be back in the current bleeding edge... Was also reported here:
https://forum.thirtybees.com/topic/3680-thirty-bees-111-pre-release-bug-hunt/page/2/?tab=comments#comment-32583

**Closed** 2022-03-30 12:05 UTC
Labels: Bug
