### ISSUE TITLE
Emails are not getting sent out on fresh 1.0.6 installation

### ISSUE THREAD

**Issue by doclucas** [thirtybees/thirtybees#598] opened 2018-09-15 14:30 UTC
They work fine on 1.0.5 and if using the upgrader from 1.0.5 -> 1.0.6 they work fine on 1.0.6, but on fresh 1.0.6, not sent.

![chrome_2018-09-15_21-15-40](https://user-images.githubusercontent.com/5753365/45587306-6ccfec00-b92e-11e8-9097-97a1a90e5403.png)

When clicking the resend button, the error appears.
Reported by Peter and reproduced by me.
First report:
https://forum.thirtybees.com/topic/1230/solved-email-error-message-when-updating-order-status-to-delivered/111

Note: test email from the admin interface (TEST YOUR EMAIL CONFIGURATION) is being sent out and delivered just fine.

**Comment by Dh42** [comment] 2018-09-15 14:32
Enable debug mode and try again, it might display the actual error.

**Comment by doclucas** [comment] 2018-09-15 14:34
Indeed it does:
Error - The following e-mail template is missing: /home/XXX/public_html/mails/gb/bankwire.txt

**Comment by Dh42** [comment] 2018-09-15 14:44
Yeah, but they might not be translated.

**Comment by doclucas** [comment] 2018-09-15 14:44
At least it won't error

**Comment by Dh42** [comment] 2018-09-15 14:44
True, it must not be pulling them over.

**Comment by Traumflug** [comment] 2018-09-15 14:47
These files should be there:
```
translations.thirtybees.com/packs/1.0.6$ tar -tvzf gb.gzip | grep bank
drwxrwxr-x mah/mah           0 2018-08-16 15:07 ./modules/bankwire/
drwxrwxr-x mah/mah           0 2018-08-16 15:07 ./modules/bankwire/translations/
-rw-rw-rw- mah/mah        6401 2018-08-15 21:19 ./modules/bankwire/translations/gb.php
-rw-r--r-- mah/mah        7528 2018-08-03 21:13 ./mails/gb/bankwire.html
-rw-r--r-- mah/mah         829 2018-08-03 21:13 ./mails/gb/bankwire.txt
```

**Comment by doclucas** [comment] 2018-09-15 14:49
Can't find any of those 3 files

**Comment by doclucas** [comment] 2018-09-15 14:52
Is that even correct config?
![chrome_2018-09-15_21-51-49](https://user-images.githubusercontent.com/5753365/45587574-9e968200-b931-11e8-8454-04afc288c812.png)

**Comment by Traumflug** [comment] 2018-09-15 15:04
Yes, config looks good. It actually looks for the right file, after all.

For finding the issue, you could look up your installation, whether the file is there as well.

**Comment by Traumflug** [comment] 2018-09-15 16:08
Apparently grabbing translations from the server failed. Can you download this file?

https://translations.thirtybees.com/packs/1.0.6/gb.gzip

That's the file where all the translations are inside, the installer should download it automatically.

If you want to look inside: despite it's name it's a .tar.gz file.

**Comment by doclucas** [comment] 2018-09-19 06:53
Just removed and reinstalled the whole TB 1.0.6 with Softaculous again.
Got this on the server (without the `gb` folder):
![image](https://user-images.githubusercontent.com/5753365/45735298-97ad8f00-bc11-11e8-881c-5a4d2398251a.png)

Then I added a new language (English GB, as seen in the screenshot 4 posts above), then checked the server, and still there was no `gb` folder.
Then in localzations -> translations, I added the GB translation:
![image](https://user-images.githubusercontent.com/5753365/45735613-a0529500-bc12-11e8-9afe-801d7ecf5a61.png)

And now the `gb` folder exist.

This is not very intuitive obviously.
The email error issue was caused because I set the default (in that case it was also the only) language to be a language that didn't have translations downloaded for it, and thus it failed without giving a clear explanation.

Some possible ways to improve this:
- Automatically download translations when a new language is added to the site and a matching translation package is found.
- Give a clearer notice when the translations are missing, with a link to the translations page
- Any other ideas you may have

**Comment by Traumflug** [comment] 2018-09-19 12:17
Well, the translation packages *are* made. In case the latest one for a particular language is missing, the one of the previous installation gets installed. If this fails as well, no languages get installed, which still gives a working shop. All these failures get reported in the installer as a warning.

Installation of a language is fairly easy: back office -> *Localization* -> *Translations*, panel *Add / Update a language*, select the language and click *Add or update language*.

The problem you experience is apparently a problem with the Softaculous package, which isn't build by thirty bees, but by Softaculous them selfs. And I wish I'd know a way to test it without setting up a whole server with cPanel.

**Comment by Traumflug** [comment] 2018-09-19 12:28
> That's installation of a translation, not installation of a language.

Installing translations also installs the language. This *Languages* -> *Add...* thing is for adding languages not yet provided on the translations server. And I certainly agree that having the latter at all, and even in a more prominent place, can be confusing.

**Comment by doclucas** [comment] 2018-09-19 16:26
Either way, let's focus on the points - this bug report is about emails not being sent out if and when those translations are missing. And there are multiple scenarios that can cause this (missing translations). None of them got anything to Softaculous, just to be clear.
These should be improved and fixed.

**Comment by Traumflug** [comment] 2018-09-19 18:27
> this bug report is about emails not being sent out if and when those translations are missing.

That's a new aspect for me. You're right, of course. In case an email template for a particular language is missing, the US-English one coming with the distribution should get used.

**Comment by doclucas** [comment] 2018-09-19 19:02
>the US-English one coming with the distribution should get used.

And what happens if the admin deleted US-English language via the BO...?

**Comment by Traumflug** [comment] 2018-09-19 19:07
Then there are no templates which could get used for sending an email.

While regular translations use the wording hardcoded in PHP, then, there's no equivalent for emails I'm aware of.

**Comment by doclucas** [comment] 2018-09-19 19:10
And then this `An error occurred while sending the e-mail to the customer` comes up and no transactional emails are getting sent out as well.
Hope it's all clear now.

**Comment by Traumflug** [comment] 2019-04-23 20:01
Probably a duplicate of #539.

**Comment by getdatakick** [comment] 2019-11-15 09:03
I'm closing this issue because as a fact of life. Thirtybees first tries to find email template in given language. If this fails, it tries to use `en` language template. If this is not found, there is nothing we can do. Nothing can be sent.

There is, however, related issue regarding deleting language. Email templates in `en` language are considered special:

- they come with thirtybees distribution
- they are used as as (preferred) translation source
- they are used as a fallback
- all modules that send emails (well, 99% of them) containes default template in `en` folder

Because of all of these, `en` email tempaltes should **not** be deleted when english language is removed from the system. It can only cause issues.

I will create separate issue for this

**Closed by getdatakick** 2019-11-15 09:03 UTC
Labels: Bug
