### ISSUE TITLE
Error on the query setting the $sqlFilter

### ISSUE THREAD

**Issue by Derbai** [thirtybees/thirtybees#601] opened 2018-09-18 17:31 UTC
https://github.com/thirtybees/thirtybees/blob/508a90061e3cdf2fa6f4ac35fefadce6c53d6f67/classes/Category.php#L271

The "1" should be removed:

WHERE 1 '.$sqlFilter.'

should be

WHERE '.$sqlFilter.'

**Comment by doclucas** [comment] 2018-09-19 07:05
Good catch. Look like a debugging attempt that was forgotten there long time ago.

**Comment by Derbai** [comment] 2018-09-19 07:12
I see after that removing the "1" the query give an error when $sqlFilter is not set. So I updated it like this:

WHERE '.(isset($sql_filter) ? $sql_filter : '1').'

Probably you can find a better solution. Anyway this one work :-)

**Comment by Traumflug** [comment] 2018-09-19 11:58
Second suggestion is much closer. Changed `$sql_filter` to `$sqlFilter`, then it actually works.

Made a commit, which should arrive on *1.0.x* in a couple of minutes. Thank you very much!

**Comment by getdatakick** [comment] 2018-10-15 07:55
I'm having a hard time understand why was this change submitted - was there actually any bug or issue?

This function is clalled twice in the core, in both cases there is no `$sqlFilter` provided. These two cases worked just fine with original code. 

So, the only explanation is that there is some module that passed `$sqlFilter` in incorrect format. If that's the case, than the **module** itself should be fixed, because it simply passes wrong arguments. 

I'm talking about this becuase this change actually broke my `revws` module. My module is passing $sqlFilter as `AND c.level_depth > 0`, which worked on all versions of thirtybees. But it's no longer work on tb 1.0.7, because there is no `1` before this sql sub-expression.

**Comment by Traumflug** [comment] 2018-10-15 09:48
As far as I can see, a filter like `c.level_depth > 0` wouldn't work with this change. Your module worked around this bug by also passing a `AND`.

Do we need a `preg_replace()` for retrocompatibility, removing the `AND`?

**Comment by getdatakick** [comment] 2018-10-15 10:56
There are couple public functions in the thirtybees codebase that accept sql fragment as a parameter, and they *expect* these sql fragments to start with `AND` or `OR`. For example [here](https://github.com/thirtybees/thirtybees/blob/1e34bdafba75c0a60e9f9bfd3ee65498b5b1ecf6/classes/Category.php#L341) or [here](https://github.com/thirtybees/thirtybees/blob/1e34bdafba75c0a60e9f9bfd3ee65498b5b1ecf6/classes/ObjectModel.php#L1472). This function is just another one.

Is it a bad design? Sure. But it's **not a bug**. Caller can tweak the query as long as passed sql fragment starts with `AND`. And it's not a workaround, that's the intended use case scenario. 

I'm really not sure why was this issue filed in the first place. I don't see any bug mentioned anywhere. The description only contains: 

> The "1" should be removed

**Closed** 2024-07-11 11:27 UTC
Labels: Bug
