### ISSUE TITLE
CSV product import - Error copying image

### ISSUE THREAD

**Issue by Hedgehog85** [thirtybees/thirtybees#806] opened 2018-12-19 21:29 UTC
During product importing, TB says “Error copying image”, and all imported products don’t have any images, while everything worked well on PS (same product tables and server). Server logs show no relevant errors, admin panel logs shown 0x 0 error during import. Tried tweaking image setting, fresh installs, different domain names, no success

**Comment by getdatakick** [comment] 2018-12-20 06:43
I think this is problem with low memory

**Comment by Hedgehog85** [comment] 2018-12-20 12:41
solved https://forum.thirtybees.com/topic/2380/csv-product-import-error-copying-image/13

**Comment by getdatakick** [comment] 2018-12-20 14:01
The root cause was fixed by commit 9dbd43c79d2b19252096067a7935b38850f58d1f

**Closed by getdatakick** 2018-12-20 14:01 UTC
