### ISSUE TITLE
Registering customer without birthday shows php notice.

### ISSUE THREAD

**Issue by toplakd** [thirtybees/thirtybees#1285] opened 2021-03-04 22:01 UTC
If template does not require entering customers birthday, the birthday gets saved as 0000-00-00 into database when customer completes registration.

This causes php notice in Customer.php
Trying to access array offset on value of type bool in
https://github.com/thirtybees/thirtybees/blob/5a60169a2d31d41cb3ca6e1ac68bf2379222c9cf/classes/Customer.php#L763

**Comment by getdatakick** [comment] 2021-03-05 17:35
@toplakd I can't reproduce. What database server are you using?

**Comment by toplakd** [comment] 2021-03-05 19:32
10.3.24-MariaDB-log-cll-lve 
Only yesterday I noticed that it happened only when new account was created (not always) and I was then also available to replicate it on my live & testing & vanilla install. 
But today I'm not able to replicate it anywhere.
That PHP notice was happening for few months now together with another PHP notice which was also always on account registration

**Comment by toplakd** [comment] 2021-03-07 12:38
Have now made sume further investigations, and as it seems it's not related to when customer registers, as during last error delete and until now no new customers got registered, but again 2x that notice came up. And both time in pairs of 2x notice on same time stamp.
![Screenshot_2021-03-07 error_log - cPanel File Manager v3](https://user-images.githubusercontent.com/39807649/110240054-58429c80-7f4a-11eb-9784-c674d7497805.png)

**Comment by getdatakick** [comment] 2021-03-08 07:27
I finally managed to reproduce this one. The notice is thrown when you open abandoned cart that is not associated with any customer. Fixed in 3828587409ba9376520ef2d8f466efc809bbfe9c

**Closed** 2021-03-08 07:33 UTC
Labels: Bug, Could not reproduce, Needs more info
