### ISSUE TITLE
Remove ISO code from the URLs for the first (default) language

### ISSUE THREAD

**Issue by Yabbertb** [thirtybees/thirtybees#1920] opened 2024-11-07 15:23 UTC
If you launch a store with only one language, then all the URLs in the store do not have the language suffix after the domain.
If the store, after some time of operation, decides to add a new language, all the URLs of the default language are spoiled and the ISO suffix of the language is added to them. With a large number of products in the store, this requires the creation of thousands of 301 redirects for the old URLs, and even so, the positions of these pages record large drops in the SERP results of search engines.
There are modules for prestashop that remove the ISO code for the default language, but I think such a serious bug should be fixed at the core level.

**Comment by getdatakick** [comment] 2024-11-08 08:47
I don't see this as a bug. This behaviour existed forever.

I agree that we could implement enhancement - settings option with three options for language iso code in url

1) current behaviour -- include iso code for multi-language shops, hide iso code for single language shops
2) always include show iso code, even for single-language shops
3) include iso code only for non-primary language

#### Workaround: 
if you need to add new language, you can always opt for multistore. Add a new store that shared everything with your primary store, and associate this store with single language only. Then use subdomains for every store:

- www.domain.com
- it.domain.com
- cz.domain.com

**Comment by Yabbertb** [comment] 2024-11-08 11:50
> I don't see this as a bug. This behaviour existed forever.

There have always been and still are thousands of serious bugs in prestashop.
Destroying all the URLs in the store, just because of adding a new language, is certainly a serious bug.

If we decide to use national domains like mydomain.uk, mydomain.de, mydomain.fr then multistore solution is a good solution.
But running subdomains like en.mydomain.com, de.mydomain.com, fr.mydomain.com is not the best solution for SEO reasons.

**Comment by getdatakick** [comment] 2024-11-08 12:36
> There have always been and still are thousands of serious bugs in prestashop. Destroying all the URLs in the store, just because of adding a new language, is certainly a serious bug.

This is by design, hence not a bug :)

> If we decide to use national domains like mydomain.uk, mydomain.de, mydomain.fr then multistore solution is a good solution. But running subdomains like en.mydomain.com, de.mydomain.com, fr.mydomain.com is not the best solution for SEO reasons.


In multistore you can assign any domain you wish. You can use national domains, or subdomains, its up to you.

**Comment by getdatakick** [comment] 2024-12-04 09:21
@Yabbertb

This enhancement has been implemented in branch issue-1920. You can test it (it's possible to update to the branch using coreupdater, or you can install it manually). 

Since this is a big change, I'd like for more people to test it before I merge it to main

**Comment by Yabbertb** [comment] 2024-12-05 04:37
Hi @getdatakick 

I did a test of all system pages of the shop, all module pages and the entire order creation process for the option:
Include language code in URLs -> Only for non-default languages
- all URLs are correct,
- on all pages the language change works correctly,
- all modules work properly,
- in PHP error logs I have ZERO errors.
Also I believe that this modification is fully working properly.

**Comment by getdatakick** [comment] 2024-12-05 09:21
Thank you @Yabbertb for the testing. @therampagerado discovered some issues with the change, it has been fixed in the branch

**Closed** 2024-12-05 09:22 UTC
Labels: Enhancement
