### ISSUE TITLE
Backoffice order edit - add discount and add product buttons disappear after one edit

### ISSUE THREAD

**Issue by NaturePinks** [thirtybees/thirtybees#824] opened 2019-01-25 19:41 UTC
Once an order is edited in backoffice - i.e., a product or discount is added or removed - the 'Add a product' and 'Add a new discount' buttons don't show up anymore.

One has to go back to orders screen and select the order again to open it. The buttons show up again on a fresh opening of the order details screen.

Thirty bees 1.0.8

**Comment by NemoPS** [comment] 2019-03-24 10:47
Working over here on the latest build, anyone else can reproduce it?

**Comment by NaturePinks** [comment] 2019-03-24 13:36
I continue to see the issue on two separate installs of 1.0.8
My sites are in production - I can take screenshots at the next edit that I do.

**Comment by Dh42** [comment] 2019-03-24 13:42
Are you using multi-store or advanced stock management? I have tested as well and I cannot reproduce it either.

**Comment by Purity1** [comment] 2019-03-24 13:58
I actually just reproduced this on my live installation.
As soon as I added a product to an order, the product added itself, but it leads to the buttons disappearing. Have to refresh the page (f5) to bring them back.

**Comment by Traumflug** [comment] 2019-03-24 14:02
Surprise, surprise, on 1.0.8 I get indeed this:

![grafik](https://user-images.githubusercontent.com/318581/54880528-bc472580-4e45-11e9-884b-93b91e908110.png)

No longer on latest 1.0.x, though, so this should be solved.

**Comment by Purity1** [comment] 2019-03-24 14:35
Great to see that this is fixed already.

I can't test this on bleeding edge because I do not have it installed, but on 1.0.8, when I reproduced this original issue, I noticed adding an item to an order also creates an active shopping cart with just that single item in it. It then continues to do this for each item you add to the order. So, say, you add 5 items to an order, it will then create 5 separate active shopping carts.

Is this intentional?

**Comment by Traumflug** [comment] 2019-03-24 14:41
Probably yes. This whole area of editing orders in back office certainly needs some cleaning. But not before the _1.1.0_ release.

Closing, as the original issue is solved. If it appears in _1.1.0_ again, please don't hesitate to open another issue. And yes, screenshots help a lot :-)

**Closed by Traumflug** 2019-03-24 14:41 UTC

**Comment by NaturePinks** [comment] 2019-03-24 18:00
Thanks for the fix. Will test it on the latest release and post back.

**Comment by NaturePinks** [comment] 2020-03-13 10:39
Issue is back in 1.1.0
