### ISSUE TITLE
Advanced EU Compliance module issue

### ISSUE THREAD

**Issue by MockoB** [thirtybees/thirtybees#104] opened 2017-02-14 20:18 UTC
At first when installed module looks almost good. Just the info on hover is hard to read because the font color. After some time here is how it looks [http://imgur.com/a/VpWKs](url) and here is how it should look [http://imgur.com/H1BxVsA](url) . After uninstalling the module the info is still there [http://imgur.com/F7zqmUw](url) and here is how it should look like [http://imgur.com/w0iM1HD](url) Here is on bees after some addition of products, refreshes etc. [http://imgur.com/Rpx8f4k](url) it looks almost perfect. After uninstalling the module and clearing the cache WITH "recompile template files if the files have been updated" option switched on, the info is cleared. With just clear cache they are still there. No caching optipons were switched on except ccc and smarty cache.

**Comment by BoBBer446** [comment] 2017-02-19 13:20
All images 404 not found, thats not okay ^^

**Comment by MockoB** [comment] 2017-02-19 15:28
I replaced all the images on another host but it is git issue or just me don't know how to upload decent link maybe :) Just copy the link and paste it in your browser and you should be able to view the pictures.

**Comment by Nobodaddy** [comment] 2017-02-20 16:07
This cache error of AEUC is a real old hat and known since August 2015: [https://www.prestashop.com/forums/topic/451323-retour-advanced-eu-compliance/page-2#entry2119149] and discussed on Github too, e. g. here [https://github.com/PrestaShop/advancedeucompliance/pull/54]. 
As a workaround you can avoid it by disabling the smarty cache. Not the best solution but it works. An attempt to fix this bug was made in *ps_legalcompliance* for PS 1.7.

**Comment by MockoB** [comment] 2017-02-20 18:17
It is really sad to hear that! Unfortunately bees project is based on 1.6.1.11 and as I can see the issue is after version 1.6.1.8. So basically we are stuck waiting the good will of the developers to solve it. Unfortunately it is impossible to start shop on German and Austrian market without that module and may be in other countries also. I hope the issue will be handled more responsibly by the bees team than the other ...

**Comment by firstred** [comment] 2017-02-20 22:24
Has anyone tried the `ps_legalcompliance` module?
Would it be better to backport that module, rather than upgrading the advanced eu compliance module?

**Comment by Nobodaddy** [comment] 2017-02-20 22:26
Nope, the solution is really poor, because it is more of another workaround because they didn't find out what caused the bug. Have a look at the hooks and you will know.

**Comment by firstred** [comment] 2017-02-20 22:34
Which leaves me wondering... How the heck did PrestaShop 1.7 get the EHI seal? https://ehi-siegel.de/shopbetreiber/ehi-siegel/pruef-kriterien-bedingungen/pruef-kriterien/

**Comment by Nobodaddy** [comment] 2017-02-21 23:34
Ha, ha, you must be kidding! None of those cerification companies (EHI, Trusted Shops, Haendlerbund etc.) proof if a certain software works properly or complies to whatever law. These are not the criteria for any  certification. It's just about a catalog of formalities, a monitoring of guidelines that often the "candidate" *himself* sets. This is the certification process those companies are paid for. It's just business!

**Comment by Traumflug** [comment] 2017-11-21 20:45
I wish I could reproduce this. Can't read this thread in french language, but I tried the instructions here: https://github.com/PrestaShop/advancedeucompliance/pull/54#issuecomment-258959921

Step one: Install module Advanced EU Compliance with default settings.

Step two: turn on caching in Backoffice -> Advanced Parameters -> Performance:

![bildschirmfoto von 2017-11-21 21-33-53](https://user-images.githubusercontent.com/318581/33095455-0e2b7c1a-cf04-11e7-8ef0-bc79321a7b81.png)

Step three: login as a customer, no employee privileges. Done.

Step four: go to the shop front page. Looks perfectly fine:

![bildschirmfoto von 2017-11-21 21-38-38](https://user-images.githubusercontent.com/318581/33095565-649f6ce6-cf04-11e7-89ca-ef361cc96850.png)

Step five: go to a product page. Looks perfect as well:

![bildschirmfoto von 2017-11-21 21-39-44](https://user-images.githubusercontent.com/318581/33095625-8ef638bc-cf04-11e7-850b-ec9d33e51bec.png)

**Comment by Traumflug** [comment] 2017-11-25 12:22
Mabe this is the reason why these duplicates are so hard to reproduce: https://github.com/thirtybees/advancedeucompliance/commit/46ad6f900e4d2c2b629ff8ffe20f17795db55d6b

Note how `{nocache}` was added to the template.

**Comment by Traumflug** [comment] 2017-11-25 14:20
Now that the bug was found to be fixed already, let me describe for the records, what the problem was and how it can be fixed in various ways.

As @eleazar/@Nobodaddy [described in the PS forum](https://www.prestashop.com/forums/topic/541316-incl-mwst-weg-zzgl-versand-weg-lieferzeit-doppelt-auf-startseite/?tab=comments#comment-2362507) correctly, module *advancedeucompliance* re-uses a single template for multiple purposes. Re-using code see usages of `dumpHookDisplayProductPriceBlock()` in *advancedeucompliance.php*. Re-usages see e.g. here: https://github.com/thirtybees/community-theme-default/blob/1.0.x/product-list-item.tpl#L62-L64 (yes, that's part of the Frontoffice template).

As soon as Smarty cache is turned on, this template gets compiled only once for all uses. All subsequent uses just replay the cached one. That's why messages apparently get duplicated: first copy is the correct one, next one means to be a different label, but gets rendered exactly like the first one.

As far as I can see, there are three ways to fix this:

1. Turn off caching for this template. One way to do this is wrapping the template into a `{nocache}...{/nocache}` pair. That's what the fix for thirty bees does. One could do about the same from within PHP, see https://www.smarty.net/docsv2/en/caching.tpl.

2. Don't re-use the template. Simply make a distinct copy for each use. That's what PS 1.7 did: https://github.com/PrestaShop/ps_legalcompliance/commit/af78a2a74da8ac7424036de36399e91f8b34fc04 I'd do it, too, if there were not more urgent things to do on other bugs. Generally, code ( = template) re-usage is a good idea, but in this use case it's pretty pointless, the template outputs entirely independent content for each use case. Worse, it needs quite some code to distinguish all the use cases.

3. Take advantage of Smartys `$compile_id` parameter to `fetch()`. Basically one sets a distinct ID for each usage, so the one template ends up in many cached versions, one cached version for each usage. See https://www.smarty.net/docsv2/en/api.fetch. Caveat: while Smarty supports this, `FrontController->display()` doesn't forward this parameter, so it'd either require an override or changes to core code.

**Closed by Traumflug** 2017-11-25 14:20 UTC
Labels: Bug, Priority: medium
