### ISSUE TITLE
Module 'thirty bees Updater' [tbupdater] is not compatible with target version of thirty bees

### ISSUE THREAD

**Issue by kintaro1981** [thirtybees/thirtybees#1705] opened 2023-07-22 15:10 UTC
If I try to go to core updater it displays this error:

```
Found 1 installed modules incompatible with thirty bees 1.5.0.
Details

Module 'thirty bees Updater' [tbupdater] is not compatible with target version of thirty bees


```

but all the modules are updated

**Comment by therampagerado** [comment] 2023-07-22 15:14
This happens because you updated to edge where the functionality of this module was moved to core. So you can safely delete tbupdater module.

Core updater is separate module responsible for the updates of the core and it **should be left installed**.

**Comment by kintaro1981** [comment] 2023-07-23 12:00
I uninstalled tbupdater and tried to update thirtybees with core updater and now I only see a blank page. :-(

**Comment by therampagerado** [comment] 2023-07-23 12:04
Revert back to your backup and check in error log module there should be some warnings or notices. Probably something is not playing nice with your php version.

**Comment by therampagerado** [comment] 2023-07-23 15:47
If  run the update again and it says everything is updated and your DB is updated you are fine.

**Comment by getdatakick** [comment] 2023-07-24 12:06
Closing as duplicate of #1693

**Closed by getdatakick** 2023-07-24 12:06 UTC
