### ISSUE TITLE
Pack quantities is wrong and the pack functionality is useless in this way.

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#558] opened 2018-07-25 08:41 UTC
Hello currently in tb and ps there's this bug:

1. We want to make a pack of 3 products A, B and C.
2. We use advanced stock management for all of them and only 1 warehouse for simplicity.
3. We put stock levels as follows: 10, 15, 20
4. When we create a pack of those products the BO tells us that the usable quantities should be 10 and we can put 10 in the quantities field for the pack if we choose 'manual input' but this is useless. If I select 'based on stock levels' the field is grey and 0. We select 'decrement both' in the pack quantities radio button.
5. We have to have 2nd (and many more) product packs where some of the items are shared with other packs so we end up with the following issue...
6. We order 1x Pack 1 and the quantities in the above scenario are correctly lowered but all other packs using some products off this 1st pack stay @ their manually set level. If we order Pack 2 then the level of Pack 2 is lowered by one and the product A become 8 (10-1-1)... But that way we can run on unavailable quantities for some pack.

The system should work like that:
1. We set a pack of products.
2. Automatically the pack quantities by default shows the lowest product level in the pack's quantities field.
3. When this product is sold with this pack or any other all quantities of packs having this product must be retracted by the sold amount.

Hope this makes sense. Please share your views on how this should work.

**Comment by getdatakick** [comment] 2022-05-20 06:41
Duplicate of issue #495

**Closed by getdatakick** 2022-05-20 06:41 UTC
Labels: Duplicate, Enhancement
