### ISSUE TITLE
'This address is not yours.' error during OPC guest checkout and Registration process type 'Only account creation'

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1745] opened 2023-12-20 13:45 UTC
Forum thread:
https://forum.thirtybees.com/topic/6424-problem-when-quick-order-without-account/#comment-48117

The bug was replicated on fresh edge test enjoinment with disabled all sorts of caches.

![image](https://github.com/thirtybees/thirtybees/assets/11251370/b512f9e3-8ef6-4637-b51b-ece0167b14c4)

**Comment by getdatakick** [comment] 2023-12-20 14:41
This is regression caused by commit c54a494997138ef5e34fd4f6ad4fa3226e7ec39c.

@eschiendorfer Emanuel, looks like this strange ajax restriction was meant for instant checkout. Do you remember why it was removed? Did it prevented some other functionality from working properly? Should we revert?

**Comment by getdatakick** [comment] 2024-01-04 13:21
Fixed by reverting the original commit.

**Closed by getdatakick** 2024-01-04 13:21 UTC
Labels: Bug
