### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1474] opened 2022-07-29 11:35 UTC
When I checked the javascript console of my shop while editing a product I saw several mixed content warnings when I checked the html source. I assume at least some of these can be easily fixed:

 - the code contains a javascript variable setting: var triggerUrl = 'http://...
 This seems to be new for TB 1.3.
 - the shop link at the top
 - the preview icon (the eye) near the top
 - the product images that become visible below the description when you click the link in "Would you like to add an image in your description? Click here and paste the given tag in the description."
 - the link to Thirty Bees in the footer
 
![http](https://user-images.githubusercontent.com/13930107/181750730-bc7f334d-a882-4553-bc4f-88c6176cf459.jpg)

**Comment by therampagerado** [comment] 2022-07-29 11:50
Very strange.

Of all of the mentioned I only have http:// for the 'Shop link' in top bar and this should not trigger mixed content as it's external link.

Are you sure you have your SEO URLs correct?

**Comment by musicpanda** [comment] 2022-07-29 18:35
I can't see a relationship with SEO urls.

**Comment by getdatakick** [comment] 2022-08-01 10:15
Couple of these are fixed in bleeding edge already. We will have to re-scrub

**Comment by musicpanda** [comment] 2022-08-01 10:55
It looks like it was largely my fault - having a wrong setting. Now only "my shop" and "Thirty Bees" are http:

**Comment by getdatakick** [comment] 2022-08-01 13:09
I can't reproduce the 'My Shop' issue, it follows current scheme properly. The same with 'Thirty Bees'. 

Regardless, these are not 'mixed content' problems, as these are outbound links that do not link any assets.

**Closed by getdatakick** 2022-08-01 13:09 UTC
Labels: Bug
