### ISSUE TITLE
vendor publicly accessible

### ISSUE THREAD

**Issue by timotheegloerfeld** [thirtybees/thirtybees#974] opened 2019-06-21 15:41 UTC
I noticed that the vendor folder is accessible by default, while the classes folder for instance is protected by an htaccess. Wouldn't it be more secure to do the same for the vendor folder?

**Comment by Traumflug** [comment] 2019-06-21 19:27
Not really more secure, because there's neither code aware of the shop software not self-sufficient code inside.

All this protection stuff needs a serious reconsideration, shops using NginX have no _.htaccess_.

**Comment by Traumflug** [comment] 2019-06-21 19:29
With this said, it turns out to be a duplicate of #592.

**Closed by Traumflug** 2019-06-21 19:29 UTC
