### ISSUE TITLE
Model definition override doesn't work for language fields

### ISSUE THREAD

**Issue by wstoch** [thirtybees/thirtybees#1927] opened 2024-11-26 10:50 UTC
**ThirtyBees Version**: Fresh install 1.5.1  

**Issue**:  

When adding a new language field or changing the definition of an existing field, the override does not work as expected.  

**Example code**:  

File: `override/classes/order/OrderMessage.php`  
```php
class OrderMessage extends OrderMessageCore
{
    public $subject;

    public function __construct($id = null, $idLang = null)
    {
        self::$definition['fields']['subject'] = [
            'type' => self::TYPE_STRING, 
            'lang' => true, 
            'validate' => 'isString', 
            'required' => true, 
            'size' => 78
        ];
        self::$definition['fields']['message'] = [
            'type' => self::TYPE_STRING, 
            'lang' => true, 
            'validate' => 'isCleanHtml', 
            'required' => true, 
            'size' => 3000
        ];
        parent::__construct($id, $idLang);
    }
}
```

**Problem:**
When attempting to save a new order message, the subject property is empty, and the message validation doesn't change.
 
In the copyFromPost function in AdminControllerCore this part of the code doesn't get overriden definition. $fields contains definition of original class.
```
/* Multilingual fields */
        $classVars = get_class_vars(get_class($object));
        $fields = [];
        if (isset($classVars['definition']['fields'])) {
            $fields = $classVars['definition']['fields'];
        }
```
Changing it like this seems to fix the problem:
```
/* Multilingual fields */
        $fields = [];
        if (isset($object::$definition['fields'])) {
            $fields = $object::$definition['fields'];
        }
 ```

**Comment by getdatakick** [comment] 2024-11-26 11:20
Closing as duplicate of issue #1766.

Fixed in 1.6.0 by commit 5de5f96760f01e5addbb5c045608c7dc5e863799

**Closed by getdatakick** 2024-11-26 11:20 UTC
