### ISSUE TITLE
Multistore: Second shop always redirects to first shop if second shop domain is entered w/o www

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1703] opened 2023-07-20 12:27 UTC
I have this error where if I enter secondshop.com it redirects me to www.firstshop.com, instead of www.secondshop.com

If I write www.secondshop.com everything is perfect.

Both domains are set up as www.domain.com in their respective secure and non secure fields.

Found a probable solution in PS' forum: https://www.prestashop.com/forums/topic/635858-2nd-store-redirects-to-main-store-multistore-redirection-problem/

**Comment by getdatakick** [comment] 2023-07-21 07:53
I don't think this is a bug, it's an expected behaviour.

Your store knows about two domains only

`www.firstshop.com`
`www.secondshop.com`

If the server receive request for any other domains (`secondshop.com`, `shop.whatever.com`, `sub1.sub2.firstshop.com`) it can't really know which store should handle it -- these domains are not assigned to the stores.

Therefore, redirect to default store takes place.

You want to redirect one domain to another domain (the fact that one is subdomain for the other is not really relevant). This is not a task that ecommerce software should perform.

You can do this using a lot of mechanisms, depending on what your stack looks like. You can create apache redirect rule, nginx redirect, cloudflare rule,...

**Closed by getdatakick** 2023-07-21 07:53 UTC

**Comment by therampagerado** [comment] 2023-07-21 08:20
I should expect it to work as singles shop works:

If I enter firstshop.com and my settings are www.firstshop.com the system redirects to www. That way the links and stuff are consistent, I doubt Google gives a shit currently for such content duplication so it's not an issue.

But then secondshop.com does not redirect to www.secondshop.com but to www.firstshop.com despite my settings in Multishop are www.secondshop.com.

Despite that as you say this is not a bug I'll try to fix it by the recommended .htaccess rule

**Comment by getdatakick** [comment] 2023-07-21 08:29
It works by sheer luck. In single-store installation, when thirtybees server receives request for domain that it does not know, it redirects to primary domain. 

The same decision process happens in multi-store installations as well. Any request for unknown domain will be redirected to primary store domain.

You can create multiple "Shop Urls" for every store. in Advanced Parameters > Multistore. You can use this to associate both www and non-www domains with a store. Thirty bees will then handle requests to both domains -- but google will complain about duplicate content, of course.
