### ISSUE TITLE
Translations not saving

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#976] opened 2019-06-25 10:17 UTC
See https://forum.thirtybees.com/topic/3152-translations-not-saving

> If I try and make a translation change of any sort, it doesn't work. Sometimes it shows in the translation mod UI, and sometimes not. I haven't found a pattern there. The only constant is that after clearing cache and reloading the affected web site pages, the translations are not taking. I check the translation file on the backend and it doesn't have my modifications included either.
>
> I'm referring to the UI within thirtybees back office. If I make adjustments to translations there, they do not save to a translations file as they should on a regular basis.

**Comment by yaniv14** [comment] 2019-06-25 10:55
I think its related https://github.com/thirtybees/thirtybees/pull/958

**Comment by getdatakick** [comment] 2019-06-25 11:35
Maybe, but #958 is not in 1.0.8 -- it affects bleeding edge / 1.1.x only. I've asked creator of the thread to confirm his version

**Comment by getdatakick** [comment] 2019-06-25 13:28
x97wehner confirmed he's on bleeding edge, so it's extremely likely this is related to, or even duplicate of issue #958

**Closed** 2020-06-08 17:15 UTC
