### ISSUE TITLE
Shop can show old cart

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#861] opened 2019-03-02 13:54 UTC
Steps to reproduce:
- Have a fresh installation.
- Go to front office, click on a product.
- Click "Add to cart".
- In the upcoming dialog, click "Continue shopping".
- Click the browser's 'back' button to go back to the front page.

Expected outcome:
- One product in the shopping cart shown in the upper right cart menu.

Actual outcome:
- An empty cart is shown.

Debugging hint:
- When not clicking "Continue shopping", but "Proceed to checkout" and then the browser's 'back' button, an empty cart is shown for a short moment as well, but gets replaced a second later. Obviously due to an Ajax request. This doesn't happen in the exact procedure above.

**Comment by NemoPS** [comment] 2019-03-23 10:52
showing 1 product over here, latest build. Can you confirm it's now fixed?

**Comment by Traumflug** [comment] 2019-03-23 15:40
Admittedly I had to try a few times. Like reloading the page just before starting the cast or varying the procedure slightly. But here's evidence:

[screencast.zip](https://github.com/thirtybees/thirtybees/files/2999538/screencast.zip)

**Comment by ksimunovic** [comment] 2019-08-01 16:29
@Traumflug Can you still reproduce this on 1.1.x? It was working normally for me

**Comment by Traumflug** [comment] 2019-08-01 17:41
Yes, I can still reproduce this with 1.1.x (with the old theme). In about 1 of 10 tries.

Eventually I managed to catch this with developer tools open:

![Bildschirmfoto vom 2019-08-01 19-22-51](https://user-images.githubusercontent.com/318581/62313830-f9759100-b491-11e9-99db-9896fc6e54ea.png)

What one can see here:
- There's an Ajax request with `?rand=...` when clicking _Add to cart_.
- Returning to the product page from the checkout page loads the product page from the cache. Unsurprising, this cached page has the wrong number of products.
- Usually there's another Ajax request with `?rand=...` after returning to the product page, which updates the number of products, but this is sometimes missing. Like in the case shown in the picture.

What one can not see in this list: when throttling network speed to GPRS, one can easily see this delayed cart update done by the Ajax request. It takes 2..3 seconds, then. Which isn't a problem, as long as it happens at all.

All this is done on latest Firefox.

**Comment by ksimunovic** [comment] 2019-08-02 09:57
@Traumflug Unfortunately, I couldn't reproduce it even once and I tried couple dozen times. Tried with latest Chrome and Firefox both and also playing with incognito, browser cache and cookies, no luck.

According to your screenshot, it seems that the ajax update is never fired which is weird because in code there's nothing very complicated going on which could be the problem. The lines in question are [ajax-cart.js#9](https://github.com/thirtybees/community-theme-default/blob/1.0.x/js/modules/blockcart/ajax-cart.js#L9) and [ajax-cart.js#169](https://github.com/thirtybees/community-theme-default/blob/1.0.x/js/modules/blockcart/ajax-cart.js#L169).

Do you have any idea how this could be reproduced more consistently?

**Comment by Traumflug** [comment] 2019-08-02 18:23
Good hint. In this line 9, change 30 to 300 and it should always reproduce. Setting this to 10, I could no longer reproduce at all, setting it to 60 or more I could always reproduce. Your computer is too fast! :-)

That said, depending on runtime performance is obviously a silly idea. This timestamp code apparently tries to detect whether the page is coming from the server or loading from cache.

I can see two solutions:
1. Not caching the page, always reloading it. This would allow to remove generation of these timestamps from JavaScript as well as template code and also dropping the Ajax request.
2. Always send the Ajax request. This would allow to remove timestamps as well (always get rid of unused code :-) ) and also to get rid of filling the cart in the HTML/Smarty template. Currently cart shows wrong content before Ajax finishes, which isn't helpful anyways. Showing just a static title _Loading..._ and no menu content at all until Ajax finished should be less computing intensive and less prone to errors.

Currently I tend to 2). Aligns probably better with all the other Ajax strategy (add, delete, delete voucher, ...) and makes HTML more friendly for server side caching. More opinions are welcome, of course.

**Comment by ksimunovic** [comment] 2019-08-03 18:00
Thanks. Regarding the solutions I agree, 2nd one would be better but this would be more of an enhancement right? This way the cart would only be rendered through PHP and the template file and fetched with AJAX, right? Then a bigger part of js code could be removed which updates the cart status and product number, making the whole generation localised to one spot. Or do you think leaving cart entierly to js is a better idea?

The bug itself could be easily quick fixed then by removing or lowering the timestamp, which I believe are only used for this.

**Comment by Traumflug** [comment] 2019-08-03 18:56
> This way the cart would only be rendered through PHP and the template file and fetched with AJAX, right? Then a bigger part of js code could be removed which updates the cart status and product number, making the whole generation localised to one spot. Or do you think leaving cart entierly to js is a better idea?

The latter. PHP/template should generate an empty/generic skeleton only, which then gets filled by the Ajax request.

It doesn't really matter whether this counts as an enhancement or not. Removing just the timestamp stuff now makes pretty sure removal of obsolete PHP/template code gets forgotten later. Once one starts in an area, one should make things reasonably complete.

**Comment by ksimunovic** [comment] 2019-08-04 12:15
Okay, if I got it right this would mean the removal of PHP generation of the whole cart and keeping just the skeleton so the Ajax request triggered on every page load can populate it?

**Comment by Traumflug** [comment] 2019-08-04 13:19
Yes, that's the idea. Can't tell how well this works out, of course. If it doesn't: too bad. But I think it's worth trying, there's a chance to speed up page loading time by a few percent.

**Comment by ksimunovic** [comment] 2019-08-06 19:53
Okay, should I try it?

**Comment by Dh42** [comment] 2019-08-06 21:14
Its kind of complicated to explain what is happening, but the fix is likely quite simple. Try adding the below to the bottom of your htaccess file @Traumflug  and see if it still happens. 

<IfModule mod_headers.c>
    Header set Cache-Control "no-cache, no-store, must-revalidate"
    Header set Pragma "no-cache"
    Header set Expires 0
</IfModule>

I tested and this fixes the issue for me, I was able to consistently reproduce it.  Basically I think the change has been on a browser level and not really something we have broken, that being said I think we need to fix it. I think the ajax request since it was executed on the cached version is not ran again, because the browser is trying to do shortcuts to make things faster. But its breaking the cart doing it.

**Comment by Traumflug** [comment] 2019-08-07 10:53
True, the problem wasn't introduced by thirty bees, it was always there (template and JS in question are untouched since the fork). On PS one can't see it, because one can't switch back to the product page fast enough. thirty bees' performance improvements made this possible and exposed the bug.

**Comment by ehohetraw** [comment] 2023-12-10 09:48
can´t reproduce.

**Closed** 2023-12-11 07:31 UTC
Labels: Bug
