### ISSUE TITLE
Wrong prices for products with a customer group discount active and combination that increases price

### ISSUE THREAD

**Issue by oliiix** [thirtybees/thirtybees#1276] opened 2021-01-28 10:48 UTC
This is tested on a completely fresh installation of TB 1.1.0.

**The issue is that when there's a customer group discount active and a product has a combination with increased price, this price is too high (about 20-30 bucks).**

**Reproduction**:
- install fresh 1.1.0 TB
- remove all taxes and tax rules and set one up for all countries that has 13% (I guess you can go with any percentage you like)
- add a product with two combinations to the coffee category, one combination has no price influence, the other increases the price for 75.- (tax incl). the base retail price (incl. tax) is set to 38.
- create merchant customer group and put a discount on the coffee category with 52.80%.
- create a user and assign him to the merchant group
- view prices in front end with the new customer and see the price for the more expensive combination be off the charts :)

**Copy of my TB-forum entry that shows all prices and their calculations**:
Here's my product settings:

TAX: 13%

No-Tax Price: 33.619469
Retail price = retail price combination A: 37.99
Retail price combination B: 113.00
Setup Combination A: no price change
Setup Combination B: imp. on price: + 75.01 (tax incl) -> tb puts 66.380531 into tax excl. field, I think it should be 66.371681

>> How is now the price calculated for my merchant group which has a category-discount of 52.8%?

My calculation of what the prices should be (prices for this group are shown w/o taxes, rounded):
Comb A: 15.87 (33.619469/100×47.2)
Comb B: 47.2 (113/1.13)/100*47.2

What TB displays in store (prices w/o tax):
Comb A: 15.87 (same as I have)
Comb B: 82.25 (far too high?)
So Combination B price in store seems far to high. How is this price being calculated? Shouldn't TB's calculation be more like the result for (113/1.13)/100*47.2 = 47.2?

Quite a high priority issue ;) Thank you so much for handling it!

**Comment by getdatakick** [comment] 2021-02-10 17:18
>TAX: 13%
> No-Tax Price: 33.619469
> Retail price = retail price combination A: 37.99
> Retail price combination B: 113.00
> Setup Combination A: no price change
> Setup Combination B: imp. on price: + 75.01 (tax incl) -> tb puts 66.380531 into tax excl. field, I think it should be ?66.371681

I don't think so.

The base price tax excl. is 33.619469. If the combination impact was 66.371681 tax excl., then final product price tax excl would be:

`33.619469 + 66.371681 = 99.99115 (tax excl) ==> 112.9899995 tax incl.`

With the value TB calculates, the result is correct

`33.619469 + 66.380531 = 100.0 ==> 113 tax incl`

**Comment by getdatakick** [comment] 2021-02-10 17:18
Please explain one more time why you think this is not correct, otherwise I will close this issue

**Comment by oliiix** [comment] 2021-02-18 08:43
I'll go over it again today as I've seen a difference between mine and your calculations that could lead to different numbers, anyway, you have forgotten to include customer groups discount. It's about the second part of my initial post -> my customer group "merchants" which has a 52.8% customer group discount on it. I will update this again, latest by tomorrow with more clear calculations or a message that all's good you you can close it.

**Comment by oliiix** [comment] 2021-02-19 09:31
so I have the same results again.

i took upper example again and I still think the calculation is about 30 bucks to high. But the prices you've mentioned are correct, those are not the problem, only one price is wrong
Normal customers see the correct prices for combination A and combination B.

Let's take my current example:
**VAT**: 13%
**Product price**: 37.99 (tax incl) / 33.619469 (tax excl)
**Combination A**: no price change
**Combination B**: price increase: 75.01 (tax incl) / 66.380531 (tax excl)

So far, all prices are correct in the shops back and frontend! Also tax excl. prices are correct in the backend.

Now add a customer group "merchants". Edit it and set price display method to "**tax excluded**", then click on "Add a category discount", select the coffee category and type in **47.2**%.  Then register a customer. You can check prices in shop, they all are correct, for both combinations. Add your customer to the merchant group and make the group his default.

Now refresh the shops frontend and check the prices again. They should now have the category discount and be displayed without tax:
Combination A: 17.75 ( = 33.619469/100*52.8) CORRECT
**Combination B: 84.13 instead of 52.8**
My calculation for combination B is **(33.619469+66.380531)/100*52.8**. Same like for combination A just including the price increase from combination B. So this makes a difference of nearly 30.-.

Hope that helps :) Don't think my calculation is off

**Comment by getdatakick** [comment] 2021-02-19 17:37
Thanks for the info. I will try to reproduce the issue on vanilla tb installation

**Comment by getdatakick** [comment] 2021-02-20 14:47
The price is calculated correctly by core. However, theme's javascript code on product page is buggy, and reconstructs the combination price badly. 

To fix this, we need to change the `updatePrice` method in `product.js` file, and base calculation on base price without group reduction

**Comment by oliiix** [comment] 2021-03-11 10:07
in my updated shop 1.2.0 (no bleeding edge) a fix for me was changing line 753 (product.js:updatePrice()) from:

basePriceWithoutTax = basePriceWithoutTax + +combination.price;
to:
basePriceWithoutTax = basePriceWithoutTax + +(combination.price * (1 - groupReduction));

It's probably no solution for shops that only show prices without tax no matter what customer group you belong to. I just have the luck that only merchant group sees prices without taxes, so this solution works for me. The thing is that the combination.price used is the one without group reduction which is wrong if there is a group reduction. So maybe just test for group reduction and then decide what line of code should be executed.

**Comment by getdatakick** [comment] 2021-03-11 14:52
The problem is that theme is trying to do business logic here. It should only display information provided by core, but in this case the information is missing.

The proper fix would be to calculate final price for (every) combination on server, and pass it to theme. 

Theme then can simply grab this pre-calculated value and display it when user changes combination.

This solution needs core support. It might also be a little bit performance killer, especially if the product has many combinations. In that case, some ajax-based solution would probably be preffered.

**Comment by getdatakick** [comment] 2021-03-13 13:33
This is a duplicate of issue #538

**Closed** 2021-03-13 13:34 UTC
Labels: Bug, Theme
