### ISSUE TITLE
Product page availability and add to cart buttons not working correctly

### ISSUE THREAD

**Issue by x97wehner** [thirtybees/thirtybees#1934] opened 2024-12-05 14:32 UTC
Note: I was about to add this to the Niara theme repo, but I think it's a bigger issue as it likely affects all compatible TB themes. Feel free to relocate if it really should only be there.

Issue: When I have a product with multiple combinations and out of stock ordering is allowed, if the sum of all combinations goes to zero or negative, then the add to cart button does not show on the product page. Also, the availability status is rendering incorrect coloring. 

This doesn't work in scenarios where one combination is still actually in stock and others are not. 

Example: Combo A has qty = 1, Combo 2 has qty = -3, and combo 3 has qty = 0. The net available for the product is -2, even though there is a combo that has available quantities. The product page will hide the add to cart button for all all combinations, even though the messaging still shows in stock. See screenshots below:

Honey combination, add to cart button is hidden and should not be since quantity is 1:
![image](https://github.com/user-attachments/assets/5ead9e9a-fb65-4060-82b6-96af4390a3dc)
I also notice in this situation that the "In Stock" label is colored with the alert red color and should not be.

Puffin combination, add to cart button is hidden correctly since quantity is -3.
![image](https://github.com/user-attachments/assets/5231b11f-e426-4424-b088-2ea4e3bd837f)

**Comment by Yabbertb** [comment] 2024-12-06 05:37
@x97wehner do you have the “Advanced stock management” option activated?
I did the test with the “Advanced stock management” option disabled and the store works fine.
For When out of stock -> Allow orders, you can order any combination, regardless of its stock quantity.
![Screenshot_20241206_062318](https://github.com/user-attachments/assets/76ac1d5c-caf2-457c-915b-029031f4725d)
![Screenshot_20241206_062453](https://github.com/user-attachments/assets/ac55010c-f839-4979-ba45-3aacabf64738)

**Comment by getdatakick** [comment] 2024-12-06 08:51
wow, what a minefield...

When product with combination is displayed, the initial data are rendered by theme `product.tpl` template. After the initial render, javascript from `product.js` will update the page to reflect values of selected combination (if no combination is selected, then default combination). 

Ideally, the page should not flicker during this initial update, because javascript should construct the same HTML as the initial render. That's not the case, though :)

There are multiple problems:

1) when product with combinations is displayed by ProductController, quantity of product itself is passed to theme. We should pass quantity information for default combination. In our example, information passed to theme was`$product->quantity = -2`. This has been fixed in commit 37b3d00559e447bbc175b5a41bf1a59cae5b394e. After the fix, the data passed to theme is `$product->quantity = 1` (or value of default combination)

2) The code in `product.tpl` hide **parent element** of buy button block (id `#add_to_cart`) when `$product->quantity <= 0`. The problem is that the parent element is hidden, and not the buy block itself. Javascript code toggles visibility of the `#add_to_cart` element, so this initial render blocked 'add to cart' button for all combinations. The fix for niara is thirtybees/niara@b2543232f50badeead10249e1b8db0d244a07635. Note that this is to some extend related to previous problem. Because quantity for all combinations were previously considered (sum = -2), the buy block was hidden for all combinations. Now, with the fix in core, the buy block would be hidden for all combinations only if the default combination quantity <= 0. Fix is theme is most important here. It will fix the issue even without core fix.

3) Javascript incorrectly toggled availability status labels. In some cases the initial label rendered by theme was not removed by javascript when switching between combinations. Fixed in commit thirtybees/niara@850ccedbd2d091cdb635b7a0b415143e4a1bcab2. This is not a critical issue, just nice to have fixed.

4) Javascript code tries to detect if other combinations can be ordered, and if so, it should displays 
`This combination does not exist for this product. Please select another combination.`. The code was buggy - it just did sum of all combinations quantities, and check that the sum > 0. This is not the case for our example (-2), so the javascript displayed `This product is no longer in stock` instead. The fix is to calculate sum of positive quantities instead. See thirtybees/niara@9606aedaed6e6bfb12a902008687d9f49889b107

**Closed by getdatakick** 2024-12-06 08:51 UTC

**Comment by x97wehner** [comment] 2024-12-06 14:00
> @x97wehner do you have the “Advanced stock management” option activated? I did the test with the “Advanced stock management” option disabled and the store works fine. For When out of stock -> Allow orders, you can order any combination, regardless of its stock quantity. ![Screenshot_20241206_062318](https://private-user-images.githubusercontent.com/144372521/393110913-76ac1d5c-caf2-457c-915b-029031f4725d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTM4NDAsIm5iZiI6MTczMzQ5MzU0MCwicGF0aCI6Ii8xNDQzNzI1MjEvMzkzMTEwOTEzLTc2YWMxZDVjLWNhZjItNDU3Yy05MTViLTAyOTAzMWY0NzI1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxMzU5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGVlMTk5MDRlNDE3Njc3ODA0ZDcwYjU5NzE1MmVhOTY2YTNhNTU2Mzk4ZTliN2RmZWU2ZTE1NTQ0ZmI0ZjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ffqAGnPqHuN-AqvZlIPbF9wyode3gX7EPHDR4HnUO2o) ![Screenshot_20241206_062453](https://private-user-images.githubusercontent.com/144372521/393110945-ac55010c-f839-4979-ba45-3aacabf64738.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTM4NDAsIm5iZiI6MTczMzQ5MzU0MCwicGF0aCI6Ii8xNDQzNzI1MjEvMzkzMTEwOTQ1LWFjNTUwMTBjLWY4MzktNDk3OS1iYTQ1LTNhYWNhYmY2NDczOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxMzU5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTA5ZjBmOWRlYTdmM2NmYTE3ODk2NWM5MzI4M2I2OThkYTFiNWM0YmM5ZWYzMzlkZTAxYmEwZWE0OGQzN2ZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FCmHl2cwKWsL3XlF2tlpJP2RyDLKn-8OyNTffUZbMH0)

You were seeing this behavior because you are allowing order of out of stock products. If that is turned off, then you would see the issue I presented. Yes, it's strange to have a negative in any inventory if not allowing order of out of stock products, but it does happen occasionally and cause this issue.

**Comment by x97wehner** [comment] 2024-12-06 14:01
> wow, what a minefield...
> 
> When product with combination is displayed, the initial data are rendered by theme `product.tpl` template. After the initial render, javascript from `product.js` will update the page to reflect values of selected combination (if no combination is selected, then default combination).
> 
> Ideally, the page should not flicker during this initial update, because javascript should construct the same HTML as the initial render. That's not the case, though :)
> 
> There are multiple problems:
> 
>     1. when product with combinations is displayed by ProductController, quantity of product itself is passed to theme. We should pass quantity information for default combination. In our example, information passed to theme was`$product->quantity = -2`. This has been fixed in commit [37b3d00](https://github.com/thirtybees/thirtybees/commit/37b3d00559e447bbc175b5a41bf1a59cae5b394e). After the fix, the data passed to theme is `$product->quantity = 1` (or value of default combination)
> 
>     2. The code in `product.tpl` hide **parent element** of buy button block (id `#add_to_cart`) when `$product->quantity <= 0`. The problem is that the parent element is hidden, and not the buy block itself. Javascript code toggles visibility of the `#add_to_cart` element, so this initial render blocked 'add to cart' button for all combinations. The fix for niara is [thirtybees/niara@b254323](https://github.com/thirtybees/niara/commit/b2543232f50badeead10249e1b8db0d244a07635). Note that this is to some extend related to previous problem. Because quantity for all combinations were previously considered (sum = -2), the buy block was hidden for all combinations. Now, with the fix in core, the buy block would be hidden for all combinations only if the default combination quantity <= 0. Fix in theme is most important one here. It will fix the issue even without core fix.
> 
>     3. Javascript incorrectly toggled availability status labels. In some cases the initial label rendered by theme was not removed by javascript when switching between combinations. Fixed in commit [thirtybees/niara@850cced](https://github.com/thirtybees/niara/commit/850ccedbd2d091cdb635b7a0b415143e4a1bcab2). This is not a critical issue, just nice to have.
> 
>     4. Javascript code tries to detect if other combinations can be ordered, and if so, it should displays
>        `This combination does not exist for this product. Please select another combination.`. The code was buggy - it just did sum of all combinations quantities, and check that the sum > 0. This is not the case for our example (-2), so the javascript displayed `This product is no longer in stock` instead. The fix is to calculate sum of positive quantities instead. See [thirtybees/niara@9606aed](https://github.com/thirtybees/niara/commit/9606aedaed6e6bfb12a902008687d9f49889b107)

Appreciate you working on this @getdatakick and getting it functioning correctly. I'll validate, but I expect you've got it corrected.
