### ISSUE TITLE
 Warehouse theme does not install

### ISSUE THREAD

**Issue by aykou** [thirtybees/thirtybees#875] opened 2019-03-12 22:20 UTC
I'm trying to install the theme "warehouse", it installs almost normal. But the modules that should be installed do not install and those that should be removed are not removed. I could even do this manually but I do not know which modules I should remove.
I tried to force the installation and now I have some errors in the modules like this:

## ThirtyBeesException  
**Argument 1 passed to Iqitcontentcreator::buildSubmenuTree() must be of the type array, null given, called in /var/www/clients/client1/web11/web/modules/iqitcontentcreator/iqitcontentcreator.php on line 667**  
 *at line* **1076** *in file* `modules/iqitcontentcreator/iqitcontentcreator.php`  
```php  
1071.    		}
1072.    
1073.    		return $return_categories;
1074.    	}
1075.    
1076. => 	public function buildSubmenuTree(array $dataset, $frontend = false, $cssgenerator = false) 
1077.    	{
1078.    		$id_lang = (int)Context::getContext()->language->id;
1079.    		$id_shop = (int)Context::getContext()->shop->id;
1080.    		$id_lang_default = (int)Configuration::get('PS_LANG_DEFAULT');
1081.    
```  
- **Iqitcontentcreator->buildSubmenuTree** - [line `667` - `modules/iqitcontentcreator/iqitcontentcreator.php`]  
 - [3 Arguments]  
```php  
662.    		$css = '';
663.    		$content = Configuration::get($this->config_name.'_content');
664.    
665.    		if (strlen($content))
666.    		{
667. => 			$content = $this->buildSubmenuTree(json_decode($content, true), false, true);
668.    			$css .=  $this->generateElementsCss($content);
669.    		}
670.    
671.    
672.    		$css  = trim(preg_replace('/\s+/', ' ', $css));
```  
```Argument [0]  

Argument [1]  

Argument [2]  
1
```  
- **Iqitcontentcreator->generateCss** - [line `412` - `modules/iqitcontentcreator/iqitcontentcreator.php`]  
```php  
407.    			}
408.    			else
409.    				Configuration::updateValue($this->config_name.'_'.$default, Tools::getValue($default));
410.    		}
411.    
412. => 		$this->generateCss();
413.    
414.    	}
415.    
416.    	public function generateElementsCss($elements)
417.    	{
```  
- **Iqitcontentcreator->_postProcess** - [line `262` - `modules/iqitcontentcreator/iqitcontentcreator.php`]  
```php  
257.    			Tools::redirect(_PS_BASE_URL_.__PS_BASE_URI__.'modules/'.$this->name.'/export/'.$file_name);
258.    		}
259.    
260.    		
261.    		if (Tools::isSubmit('submitIqitcontentcreatorModule'))
262. => 			$this->_postProcess();
263.    		
264.    		$this->context->smarty->assign('module_dir', $this->_path);
265.    		$output = $this->context->smarty->fetch($this->local_path.'views/templates/admin/configure.tpl');
266.    
267.    		$output .= '<div class="panel clearfix">
```  
- **Iqitcontentcreator->getContent** - [line `1648` - `controllers/admin/AdminModulesController.php`]  
```php  
1643.                                }
1644.                                if (count($this->errors)) {
1645.                                    continue;
1646.                                }
1647.                                // Get the return value of current method
1648. =>                             $echo = $module->{$method}();
1649.                                // After a successful install of a single module that has a configuration method, to the configuration page
1650.                                if ($key == 'install' && $echo === true && strpos(Tools::getValue('install'), '|') === false && method_exists($module, 'getContent')) {
1651.                                    Tools::redirectAdmin(static::$currentIndex.'&token='.$this->token.'&configure='.$module->name.'&conf=12');
1652.                                }
1653.                            }
```  
- **AdminModulesControllerCore->postProcessCallback** - [line `1511` - `controllers/admin/AdminModulesController.php`]  
```php  
1506.                }
1507.            }
1508.    
1509.            // Call appropriate module callback
1510.            if (!isset($ppmReturn)) {
1511. =>             $this->postProcessCallback();
1512.            }
1513.    
1514.            if ($back = Tools::getValue('back')) {
1515.                Tools::redirectAdmin($back);
1516.            }
```  
- **AdminModulesControllerCore->postProcess** - [line `251` - `classes/controller/Controller.php`]  
```php  
246.            if ($this->checkAccess()) {
247.                if (!$this->content_only && ($this->display_header || (isset($this->className) && $this->className))) {
248.                    $this->setMedia();
249.                }
250.    
251. =>             $this->postProcess();
252.    
253.                if (!empty($this->redirect_after)) {
254.                    $this->redirect();
255.                }
256.    
```  
- **ControllerCore->run** - [line `837` - `classes/Dispatcher.php`]  
```php  
832.                if (isset($paramsHookActionDispatcher)) {
833.                    Hook::exec('actionDispatcher', $paramsHookActionDispatcher);
834.                }
835.    
836.                // Running controller
837. =>             $controller->run();
838.            } catch (PrestaShopException $e) {
839.                $e->displayMessage();
840.            }
841.        }
842.    
```  
- **DispatcherCore->dispatch** - [line `63` - `admin/index.php`]  
```php  
58.    if (!isset($_REQUEST['controller']) && isset($_REQUEST['tab'])) {
59.        $_REQUEST['controller'] = strtolower($_REQUEST['tab']);
60.    }
61.    
62.    // Prepare and trigger admin dispatcher
63. => Dispatcher::getInstance()->dispatch();
```

**Comment by getdatakick** [comment] 2019-04-17 05:55
Duplicate of issue #815

**Closed by getdatakick** 2019-04-17 05:55 UTC
