### ISSUE TITLE
Installation is not allowing editing of CMS, Category, or Product page columns

### ISSUE THREAD

**Issue by Dh42** [thirtybees/thirtybees#501] opened 2018-05-04 16:07 UTC
Here is a forum post for reference, https://forum.thirtybees.com/topic/1713/set-columns-for-theme  The issue is in the installed meta.

**Comment by getdatakick** [comment] 2018-09-06 09:06
duplicate of issue #582

**Closed by getdatakick** 2018-09-06 09:06 UTC
