### ISSUE TITLE
Empty translations cause problems

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#879] opened 2019-03-18 12:55 UTC
The Prestashop default is to leave phrases without a translation out of the translation files. 

However, Thirty Bees has chosen to keep them in - probably in the hope that someone will provide a translation for the missing strings.

Unfortunately the string generation code sees the resulting empty string as a valid translation. As a consequence you don't see the English version when a translation is missing but instead an empty space.

See also this issue: https://forum.thirtybees.com/topic/2614-solved-bug-in-the-french-translation-if-it-is-update-with-the-backoffice-add-update-a-language-function/

**Comment by getdatakick** [comment] 2019-04-17 09:26
Closing as duplicate of issue #890

**Closed by getdatakick** 2019-04-17 09:26 UTC
