### ISSUE TITLE
Geoip review

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#927] opened 2019-05-06 20:08 UTC
That's a meta-issue to not forget issues in this area.

----
From https://github.com/thirtybees/thirtybees/issues/376#issue-264829356:

> It detects `en-us` via the browser, but applies `nl-nl` as soon as it detects the country via the IP address. This happens **after** most important functionality has been intialized (spoiler: that's way too late!) 

----
From https://github.com/thirtybees/thirtybees/issues/376#issuecomment-489318775

> I found this : https://github.com/sherpya/geolite2legacy
> 
> The last archive (2018-12-11) contains a "dat file" dated from 2018-03-27 ... no updates since
> 
> P.S : by the way, after january 2019, you still can download there :
https://web.archive.org/web/20181211081730/http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz

----
TODO: Test GeoIP and find a solution if it doesn't work. Like linking to this archive.org database file rather than having a broken link.

**Comment by Captain-FLAM** [comment] 2019-05-11 10:11
After testing the conversion, it doesn't work !
I made my own address form that fill automatically from the visitor ip ...
And the town where I live is wrong !!
So I switch back to the original .dat from MaxMind, even if it's outdated 2018-03-27 but at least it works !
BTW, I also tested with many ip from different countries (catched with my torrent software) ...

So, I think the best thing is to update TB to work with the last version :
https://github.com/maxmind/GeoIP2-php

**Comment by bdacus01** [comment] 2019-08-08 21:20
I wasnt sure which issue you want this in.  After upgrading to 1.1.0  GeoLocation is broken again.

`/**
1903:     * Geolocation management.
1904:     *
1905:     * @param Country $defaultCountry
1906:     *
1907:     * @return Country|false
1908:     *
1909:     * @since   1.0.0
1910:     *
1911:     * @version 1.0.0 Initial version
1912:     */
1913:    protected function geolocationManagement($defaultCountry)
1914:    {
1915:        if (!in_array($_SERVER['SERVER_NAME'], ['localhost', '127.0.0.1'])) {
1916:            /* Check if Maxmind Database exists */
1917:            if (@filemtime(_PS_GEOIP_DIR_._PS_GEOIP_CITY_FILE_)) {
1918:                if (!isset($this->context->cookie->iso_code_country) || (isset($this->context->cookie->iso_code_country) && !in_array(strtoupper($this->context->cookie->iso_code_country), explode(';', Configuration::get('PS_ALLOWED_COUNTRIES'))))) {
1919:                    $gi = geoip_open(realpath(_PS_GEOIP_DIR_._PS_GEOIP_CITY_FILE_), GEOIP_STANDARD);
1920:                    $record = geoip_record_by_addr($gi, Tools::getRemoteAddr());
1921:
1922:                    if (is_object($record)) {
1923:                        if (!in_array(strtoupper($record->country_code), explode(';', Configuration::get('PS_ALLOWED_COUNTRIES'))) && !FrontController::isInWhitelistForGeolocation()) {
1924:                            if (Configuration::get('PS_GEOLOCATION_BEHAVIOR') == _PS_GEOLOCATION_NO_CATALOG`

This is the debug file from the red highlighted line is 1919.  I double check with both a converted DB and an Old one.  the system shows 500 error either way with this debug.  I have to turn of GeoLocation to have the system function.

**Comment by getdatakick** [comment] 2019-11-06 09:30
Closing as duplicate of issue #828

**Closed by getdatakick** 2019-11-06 09:30 UTC
Labels: Enhancement
