### ISSUE TITLE
Unnecessary warning message on order page in payment section

### ISSUE THREAD

**Issue by bart-lunika** [thirtybees/thirtybees#347] opened 2017-08-28 07:08 UTC
On the order page, a message appears in the payment section that the full amount has not been payed. But it has! Not really a showstopper, but this message should not appear when the payment is correct. It appears since the upgrade to version 1.0.3 of Thirtybees.

![message](https://user-images.githubusercontent.com/29667165/29762741-58a2b06e-8bd0-11e7-8710-094928a19777.jpg)

**Comment by elund** [comment] 2017-08-28 09:58
Same problem here after upgrading from 1.0.2 to 1.0.3:
![image](https://user-images.githubusercontent.com/6267400/29768850-22abeb16-8be8-11e7-9076-2fbcc838f0bf.png)

**Comment by firstred** [comment] 2017-08-30 11:29
That's strange. Nothing has changed here between 1.0.2 - 1.0.3 :O 

Seen the logic in the template it only shows the error if the rounded amounts are different (which is not the case) or a refund is made. In all other cases the warning has to stay hidden, so here's my question:
Did you guys refund (part of) the order?

**Comment by bart-lunika** [comment] 2017-08-30 12:00
No refund at all. It shows up at all new orders that are paid.

**Comment by elund** [comment] 2017-08-30 14:29
Also no refunds here. The warning is shown on all paid orders - also on the old orders.

**Comment by firstred** [comment] 2017-08-31 09:50
Strange, I cannot reproduce and find it. Which payment modules do you have installed?

**Comment by elund** [comment] 2017-08-31 10:14
I don't think it's related to the payment modules. I use the bank transfer module, a MobilePay module and this module from ePay: [http://www.epay.dk/moduler-til-epay/prestashop-betalingsmodul.asp].
All payment modules are affected by the warning.
My shop is migrated from PrestaShop 1.6 and updated two times afterwards.

**Comment by firstred** [comment] 2017-08-31 10:18
I was thinking about template overrides, since the logic consists of just one line, this: https://github.com/thirtybees/thirtybees/blob/58790c2a9d79cffec8507345cbacdbc4395f14c9/admin-dev/themes/default/template/controllers/orders/helpers/view/view.tpl#L398

Maybe one of the variables is cast to a float, that's the only problem I could think of atm.

**Comment by bart-lunika** [comment] 2017-08-31 10:19
I use Mollie as payment provider. But in one of your first comments you mentioned something about rounding. Can it be that it has something todo with the rounding settings?
![rounding](https://user-images.githubusercontent.com/29667165/29918682-94681530-8e46-11e7-99e7-60b81107e8d8.JPG)

**Comment by firstred** [comment] 2017-08-31 10:23
Seen the fact that the rounding results in exactly the same numbers I don't think that rounding is the issue here.

**Comment by firstred** [comment] 2017-08-31 10:36
Maybe it's just a matter of relaxing the check a bit.

Can you try to find the line and replace `===` with `==` ?

**Comment by bart-lunika** [comment] 2017-08-31 11:55
I changed the code and replaced === with == and that seems to fix the issue! The message is not displayed anymore.

**Comment by firstred** [comment] 2017-08-31 11:56
Alright, let's keep it open until it is actually merged. I milestoned this issue for 1.0.4

**Comment by bart-lunika** [comment] 2017-08-31 11:58
Ah sorry for closing. Thanks for the help and feedback!

**Comment by firstred** [comment] 2017-08-31 12:00
Thanks for the confirmation!

**Comment by firstred** [comment] 2017-11-30 17:12
Double-check = OK

**Closed by firstred** 2017-11-30 17:12 UTC
Labels: Bug, Estimate: S, Priority: critical, Resolved
