### ISSUE TITLE
Admin: Product images not shown

### ISSUE THREAD

**Issue by firstred** [thirtybees/thirtybees#175] opened 2017-04-12 10:53 UTC
![noproductimages](https://cloud.githubusercontent.com/assets/6775736/24954281/fbb93fe8-1f7e-11e7-8c5f-16044edeb070.png)

**Comment by Traumflug** [comment] 2019-04-14 18:58
Huh, closed without a fix? I just found the exactly same on current _1.0.x_ (_1.0.8+_).

Steps to reproduce:
- Have a default installation.
- Look up product images in back office to find out the image number of an image related to a product.
- Run a SQL query like this:
    ```sql
    SELECT * FROM `tb_image_lang` WHERE `id_image` = <image number>;
    ```
- Delete these entries in table `tb_image_lang`.
- Go back to back office, reload the page and see how image count is the same as before, but the image is no longer listed.

Investigation so far goes like this:
- Image count (panel header bar) counts the image, because this code counts all images belonging to a product: https://github.com/thirtybees/thirtybees/blob/1.0.x/controllers/admin/AdminProductsController.php#L4935-L4940
- Images actually shown, however, require a matching entry in table _tb_image_lang_: https://github.com/thirtybees/thirtybees/blob/1.0.x/classes/Image.php#L148-L163
- Unsurprising result: if there are product images without an image entry, number in the header and count of items in the list don't match.

While this looks a bit like a broken database, such language-less images work just fine in front office. It also looks like such situations can get solved by more defensive code.

Proposed solution:
- In `Image::getImages()`, allow a language of null/0, which then returns all images, regardless of language.
- On the back office product page, list images regardless of language. The only language-specific thing is their caption, after all. Doing so, one can see language-less images and edit them. Editing them then adds the language entry, fixing the database on the fly. One could even argue that one should remove a language entry if all captions are empty. Making the database smaller, speeding up things a bit.
- In _AdminProductsController_, remove the custom query for counting images in favor of counting the array returned by `Image::getImages()`. This not only removes an uncached DB query, it also makes sure both counts match.

I'll try to implement this to see how it works out.

**Comment by Traumflug** [comment] 2019-04-15 18:38
Should be fixed with the commits listed above.

**Closed by Traumflug** 2019-04-15 18:38 UTC
