### ISSUE TITLE
Tax & shipping fee calculation bug in AEUC

### ISSUE THREAD

**Issue by 30knees** [thirtybees/thirtybees#326] opened 2017-07-30 07:42 UTC
As discussed [here](https://forum.thirtybees.com/topic/584/bug-in-eu-advanced-compliance-with-shipping-taxes), there's a bug in the AEUC. 

**Problem**

- tb takes the shipping price as including taxes.
- AEUC takes the shipping price as excluding taxes.
- Because of this, when “Proportionate tax for shipping and wrapping” is enabled for AEUC, the actual shipping fee is calculated dynamically based on the proportionate tax rate of the goods in the cart. This means that the final shipping fee cannot be stated in advance to the customer. This is both inconvenient for the merchant and the customer and in violation of EU law, which requires that the shipping price needs to be stated in advance.

**Solution**
- AEUC should take the shipping price as including taxes.

**Comment by Nobodaddy** [comment] 2017-07-30 09:04
You can find the bug in function *getPackageShippingCost* of class **Cart.php**
It starts absolutely right line 1882 

           if (Configuration::get('PS_ATCP_SHIPWRAP')) {
                // With PS_ATCP_SHIPWRAP, pre-tax price is deduced
                // from post tax price, so no $carrier_tax here
                // even though it sounds weird.
                $carrierTax = 0;
                (...)

But it ends wrong from line 2003 on, because because the avaerage tax is **added** to the shipping costs and not  **deducted** from this figure which would be correct:

        if (Configuration::get('PS_ATCP_SHIPWRAP')) {
            if ($useTax) {
                // With PS_ATCP_SHIPWRAP, we apply the proportionate tax rate to the shipping
                // costs. This is on purpose and required in many countries in the European Union.
                $shippingCost *= (1 + $this->getAverageProductsTaxRate());
            }

**Comment by Nobodaddy** [comment] 2017-07-30 10:12
Solution: [https://github.com/thirtybees/thirtybees/pull/327](https://github.com/thirtybees/thirtybees/pull/327)

**Comment by doclucas** [comment] 2018-08-30 16:03
Hasn't this been fixed with this?
https://github.com/thirtybees/thirtybees/pull/327
https://github.com/thirtybees/thirtybees/pull/327/commits/cd8a332597a9aea5d918f969ac337c0fa37e35e6

**Comment by mke-tb** [comment] 2019-08-25 20:51
@30knees who will take a look and let us know whether it is still reproducible. Thanks!

**Comment by 30knees** [comment] 2020-11-19 10:30
Sorry, this totally slipped me. 

I'm running the latest bleeding edge 3.1.3 of AEUC.

Now, when I activate "Proportional taxes" in AEUC, the option to set how taxes in the carrier area disappears. But, when I do that, I get this as an invoice, regardless of the taxes setting in the carrier area before activating "Proportional taxes": 

![image](https://user-images.githubusercontent.com/30377771/99654226-4f40c480-2a5a-11eb-88a3-8f2998eed080.png)

5% of 4.80 is obviously not 0, so something is wrong.

**Comment by 30knees** [comment] 2020-11-22 10:53
Actually, for new orders it does work but with the mistake as described below. The carrier needs to have a tax rate set. But then shipping gets calculated proportionally and taxes are added and not deducted:

> You can find the bug in function _getPackageShippingCost_ of class **Cart.php**
> It starts absolutely right from line 1882:
> 
> ```
>        if (Configuration::get('PS_ATCP_SHIPWRAP')) {
>             // With PS_ATCP_SHIPWRAP, pre-tax price is deduced
>             // from post tax price, so no $carrier_tax here
>             // even though it sounds weird.
>             $carrierTax = 0;
>             (...)
> ```
> 
> But it ends wrong from line 2003 on, because with AEUC option enabled the tax is **added** to the shipping costs and not **deducted** from this figure which would be correct:
> 
> ```
>     if (Configuration::get('PS_ATCP_SHIPWRAP')) {
>         if ($useTax) {
>             // With PS_ATCP_SHIPWRAP, we apply the proportionate tax rate to the shipping
>             // costs. This is on purpose and required in many countries in the European Union.
>             $shippingCost *= (1 + $this->getAverageProductsTaxRate());
>         }
> ```

**Comment by 30knees** [comment] 2020-11-26 17:45
I deleted the carrier and did everything anew. It works!

The steps are:

1. Disable AEUC. 
2. Choose **No tax** for the tax rate.
3. Enable AEUC.
4. Activate proportional calculation. 
5. Set the shipping cost.

@getdatakick This fix works (though now the line numbers have changed): https://github.com/thirtybees/thirtybees/pull/327

**Comment by 30knees** [comment] 2020-12-16 21:16
Update: Prestashop 1.6 cart.php from https://github.com/PrestaShop/PrestaShop-1.6/blob/master/classes/Cart.php fixes the bug.

**Comment by getdatakick** [comment] 2021-03-23 13:45
Fixed by commit 2eb944b5813c7b0b088c4888060baadb6c85453d (and previous one)

**Closed by getdatakick** 2021-03-23 13:45 UTC
Labels: Bug
