### ISSUE TITLE
UpdateProductImageShop error

### ISSUE THREAD

**Issue by Derbai** [thirtybees/thirtybees#556] opened 2018-07-23 17:18 UTC
function ajaxProcessUpdateProductImageShopAsso()

the INSERT query need to be fixed as follow

\'NULL\'

Flat NULL return error on db insert

**Comment by doclucas** [comment] 2018-08-22 15:52
Do you mean this line?
`$res = Db::getInstance()->execute('INSERT INTO '._DB_PREFIX_.'image_shop (`id_product`, `id_image`, `id_shop`, `cover`) VALUES('.(int) $idProduct.', '.(int) $idImage.', '.(int) $idShop.', NULL)');`

**Comment by doclucas** [comment] 2018-08-22 18:34
I don't see that function being used anywhere in the code.
Just curios, when do you see the error? What action/steps do you perform?

**Comment by Derbai** [comment] 2018-08-22 19:02
It is used on AdminProduct when you add image on shop clicking on the checkbox

**Comment by doclucas** [comment] 2018-08-22 19:51
Can you please post some screenshots? I can't find what you mean.

**Comment by Derbai** [comment] 2018-08-22 20:02
![screenshot-www italian-boutique com-2018-08-22-22-00-55](https://user-images.githubusercontent.com/13482186/44487657-176a2d00-a657-11e8-921f-637ea3169d7f.png)

**Comment by doclucas** [comment] 2018-08-22 20:33
Thanks. I guess that's why I couldn't find it. You have multishop.

**Comment by doclucas** [comment] 2018-08-23 11:32
I can't find even a single file in the 1.0.6 release that has occurrence of `ajaxProcessUpdateProductImageShopAsso`
Where is this function used?

**Comment by Traumflug** [comment] 2018-08-23 11:37
```sh
$ grep --exclude-dir cache --exclude-dir filemanager --exclude-dir modules.off --exclude-dir themes.off --exclude-dir vendor --exclude-dir jquery --exclude-dir ace -rn ajaxProcessUpdateProductImageShopAsso
controllers/admin/AdminProductsController.php:1448:    public function ajaxProcessUpdateProductImageShopAsso()
```

**Comment by doclucas** [comment] 2018-08-23 11:37
Yes, that's where the function gets declared.
Where is it being used?

**Comment by Traumflug** [comment] 2018-08-23 11:46
One can't grep for the call, because the method name gets computed. That's one of the typical strategies in thirty bees code. In this particular case, it gets computed in `AdminControllerCore->postProcess()`

**Comment by doclucas** [comment] 2018-08-23 11:58
Ohhh, interesting. Thanks for enlightening me. :)
Then, I guess adding those missing quotes to `LIMIT` as the OP wrote should be simple enough to close this issue. Right?

**Comment by doclucas** [comment] 2018-09-04 12:00
I have tested this and it works fine for me using `NULL` on TB 1.0.6, so not sure why you are having issues.
Changing it to `'NULL'` basically inserts `0` to the `cover` column instead of `NULL`, which is the equivalent to:
```
$res = Db::getInstance()->execute('INSERT INTO '._DB_PREFIX_.'image_shop (`id_product`, `id_image`, `id_shop`, `cover`) VALUES('.(int) $idProduct.', '.(int) $idImage.', '.(int) $idShop.', 0)');
```
What error do you get on DB insert? And can this be reproduced?
Have you tried on TB 1.0.6?

**Comment by getdatakick** [comment] 2019-11-06 13:31
Related to issue #792

**Closed** 2023-08-10 07:27 UTC
Labels: Bug
