### ISSUE TITLE
High res images don't show up

### ISSUE THREAD

**Issue by MockoB** [thirtybees/thirtybees#129] opened 2017-02-28 08:19 UTC
When the option "Generate high resolution images" in preferences/images is switched on the images are actually created in product images folder but they don't display on devices with high density screens. The pictures which are displayed are still the 1x ones. The only media queries I found are in admin/themes/default/sass/vendor/bootstrap-sass/mixins/_image.scss but I suppose they are just for the background image.

**Comment by firstred** [comment] 2017-03-02 19:43
Is this about the community theme?

**Comment by MockoB** [comment] 2017-03-02 19:48
I tried it on both TB and PS. Neither on one the high res images show, I am testing on my iPhone, iPad and pic monitor, they all show the X1 images. I believe you also have at least high res smart phone and you can check it.

**Comment by MockoB** [comment] 2017-03-02 19:50
And one more thing. Does the theme has anything to do with this option? I believe no matter what template you use it should work,  after all it is base feature.

**Comment by firstred** [comment] 2017-03-02 19:50
Trying to figure that out right now

**Comment by firstred** [comment] 2017-03-02 19:59
Ahh, now I understand. It generates images with a `2x-` prefix. These should be set as the `src` attribute if the option is enabled. Much better would have been to add the response `srcset` attribute, but this has to be supported by themes.

**Comment by kpodemski** [comment] 2017-03-02 20:00
It generates images with a 2x suffix and there's a javascript which handle the replacing of the `src` attribute

**Comment by firstred** [comment] 2017-03-02 20:02
Yeah, it does have to be fixed in the theme. The source files weren't okay.

Here's what to do:
- Take this line: https://github.com/thirtybees/community-theme/blob/bf29231a435a9831ef0ca4aee0157746e082ac85/themes/community-theme-16/js/global.js#L123
- Change `if (highDPI && $('.replace-2x').css('font-size') == '1px') {` to `if (highDPI && $('.replace-2x')) {` (somehow the check doesn't work)
- Then it will request all the alternatives with a `2x` suffix
- If they are larger than the current ones, the `src` attribute will be replaced, otherwise the same files are kept

**Comment by firstred** [comment] 2017-03-02 20:03
Orrr maybe a theme has to apply that wierd CSS thingy (`font-size: 1px`). I'm confused...

**Comment by MockoB** [comment] 2017-03-02 20:04
Please tell me what to do when you clear it out :) and I hope this feature will run with the theme I plan to buy?

**Comment by firstred** [comment] 2017-03-02 20:13
Just try the upper one first.

**Comment by MockoB** [comment] 2017-03-02 20:25
Nope, nothing changed.

**Comment by firstred** [comment] 2017-03-02 20:31
Then your source files aren't bigger.

**Comment by MockoB** [comment] 2017-03-02 20:45
Actually the source files are 1328x1000, but that does nothing to do with the issue. When I change the name from thickbox_default2x to thickbox_default and open it on ipad than the picture is sharp enough (same with other thumbnails). That means the x2 images are created (and they are because I see them in the folder)  but they just refuse to open on devices with high resolution screens. The way I understand it as non programmer is that the site doesn't get that it is visited by such device and doesn't serve the correct images. Please google retina images, it is hard for me to explain it. 
Did you checked that file _images.scss you will understand it I believe when you see it.

**Comment by firstred** [comment] 2017-03-02 20:51
Yeah that file has nothing to do with it.

I think the implementation is pretty crappy.

Here's something new you can try (just replace the whole function `highdpiInit` in the file `global.js`):
```js
function highdpiInit() {
  if (typeof highDPI === 'undefined') {
    return;
  }

  if (highDPI && $('.replace-2x')) {
    var els = $('img.replace-2x').get();
    for (var i = 0; i < els.length; i++) {
      var elem = els[i];
      src = elem.src;
      extension = src.substr((src.lastIndexOf('.') + 1));
      var twiceSrc = src.replace('.' + extension, '2x.' + extension);
      elem.attr('srcset', twiceSrc + ' 2x');
    }
  }
}
```

**Comment by firstred** [comment] 2017-03-02 20:56
Try this:
```js
function highdpiInit() {
  if (typeof highDPI === 'undefined') {
    return;
  }

  if (highDPI && $('.replace-2x')) {
    var els = $('img.replace-2x').get();
    for (var i = 0; i < els.length; i++) {
      var elem = els[i];
      src = elem.src;
      extension = src.substr((src.lastIndexOf('.') + 1));
      var twiceSrc = src.replace('.' + extension, '2x.' + extension);
      $(elem).attr('srcset', twiceSrc + ' 2x');
    }
  }
}
```

**Comment by MockoB** [comment] 2017-03-02 21:01
Please be more specific which lines to replace with the above code. It looks like you are overestimating me :)

**Comment by MockoB** [comment] 2017-03-02 21:02
And does the empty space in the last line of code ' 2x' of meaning?

**Comment by firstred** [comment] 2017-03-02 21:03
lol

Not sure if I can make it any easier, but you will have to look for this in the file `/themes/<theme name>/js/global.js` (https://github.com/thirtybees/community-theme/blob/bf29231a435a9831ef0ca4aee0157746e082ac85/themes/community-theme-16/js/global.js#L118-L135) and replace it with the codeblock above.

**Comment by firstred** [comment] 2017-03-02 21:03
that's how `srcset` works. It lets the browser determine what to use: https://www.sitepoint.com/how-to-build-responsive-images-with-srcset/

**Comment by MockoB** [comment] 2017-03-02 21:28
Still the same :( Please check this link with your smartphone http://www.krasoti.bg/26-druzi-i-geodi (it should be high res of course). Then dowload some of the pictures and upload it on TB and try to view it again with your smartphone. If you need I may send you the source image of the products. I have to turn off my pc because my 7 months old son has to sleep :) Please tell me how may I be usefull to solve the issue. I will do my homework and read tonight how srcset work :)

**Comment by kpodemski** [comment] 2017-03-02 21:30
And the mechanism is working fine, see:
![image](https://cloud.githubusercontent.com/assets/2137763/23527859/d4d0c4c0-ff97-11e6-8e61-c816af6ca703.png)

**Comment by MockoB** [comment] 2017-03-02 21:32
Sure it is, on my 1.5 store with retina module installed ;)

**Comment by kpodemski** [comment] 2017-03-02 21:33
What is the url to the store where the mechanism doesn't work?

**Comment by MockoB** [comment] 2017-03-02 21:34
It is localhost TB and PS test installations.

**Comment by firstred** [comment] 2017-03-02 21:43
It doesn't generate images with the `@2x` prefix here, just `2x`.

**Comment by firstred** [comment] 2017-03-02 21:44
suffix, uuarhgh learn some bloody English

**Comment by MockoB** [comment] 2017-03-02 22:07
I didn't quite get what you mean with that, may be my English ... And what is the point of the generated images? Or they are just supposed to use more storage, please explain? Most people are using devices with high density pixel screens, they don't care about prefix or suffix, they need clear images but they will not receive it with TB or PS. How can I achieve same effect on TB as the link above? Don't forget I am not a programmer just ignorant merchant :)

**Comment by firstred** [comment] 2017-03-02 22:46
It's not that easy. This has been implemented incorrectly for a while in the core and needs to be improved first.

**Comment by MockoB** [comment] 2017-03-03 21:38
I found interesting and detailed article about srcset attribute https://ericportis.com/posts/2014/srcset-sizes/ of course I am not smart enough to understand it but I liked the pictures :) the thing that bothers me is the browser compatibility, I saw that I.E. doesn't support it,  neither older safari versions... But if I understood it right this is the future especially with those constantly changing and improving screens, hd, 4k, 8k and so on ... I was going to suggest you the following solutions  http://retinaimag.es or http://imulus.github.io/retinajs/ it looks simple enough for you to implement, especially when the images are already generated. Is it the best option to use srcset attribute with the future in mind or we could use those js examples above?

**Comment by firstred** [comment] 2017-03-03 21:41
Great suggestion. I think PrestaShop tried to copy retinajs but as always came up with a half-baked potato. If we can replace the highdpi function in `global.js` it could work, but this change will have to be adopted by all theme makers first.

**Comment by MockoB** [comment] 2017-03-03 21:49
So my option is to buy a template which already implemented it? There are such templates but unfortunately the ones I like don't support retina images :( will it be that difficult to implement the feature in every theme on the market? Some king of module may be, like the one I have for my 1.5 store?

**Comment by firstred** [comment] 2017-03-04 00:12
Nope. None of those options work. You or a developer will have to dig into the code to get the best results.

**Comment by mke-tb** [comment] 2019-08-25 14:20
Hey @MockoB, I checked the website you shared in this issue (krasoti.bg) and it looks like you have `@2x` URLs in your image `src` attributes. Does that mean this issue is no longer reproducible or you did it manually? We need to know so we either close this issue or prioritize a fix.

**Comment by MockoB** [comment] 2019-08-25 14:29
Hi @mke-tb, that site is running on ps 1.5.6 and there was module I bought to run hi res images.
So I don't know if it's solved recently on tb or not, but when I was interested in the project, it was not solved yet.

**Comment by Traumflug** [comment] 2019-08-25 14:55
I'm not aware of success reports with high-res images and there are more recent reported issues (like #506), so before closing this, a good chunk of testing should happen.

**Comment by MockoB** [comment] 2019-08-25 16:31
It should be easy implementation, as far as I remember the srcset attribute is already implemented in the default template. So I believe no more than one line should be added for the images to work on high density screens. Of course it will work just for x2 images and there are x3 and x4 already. But x2 showing is a good starting point.

**Comment by mke-tb** [comment] 2019-08-26 21:44
@MockoB There is one thing I can't get right in my head, how exactly would you expect it to work? Should just add `@2x` suffices to images or actually generate them? Please note that there is no way to properly generate an image because `@2x` should mean doubling the resolution which would break the quality. Not to mention duplicating assets and maybe with increased size.

Or the initial problem here is having weird output on retina devices because of not having `@2x` suffix on image URLs?

**Comment by MockoB** [comment] 2019-08-27 05:45
@mke-tb that's not something you should worry about. Prestashop already implemented the "double" images they or thirty bees just never made use of it. 
You could find the feature in preferences/images/generate high resolution images - yes/no. Once the feature is enabled every time you upload an image, x2 version is also created.
Just the srcset and sizes attributes should be added I believe for every image asset used in the theme.

**Comment by mke-tb** [comment] 2019-08-27 06:39
@MockoB Thanks, yes, after further investigation, I realized that we might just need to point to the correct file. I am hoping to look into this in the following days. Thank you for your contribution.

**Comment by MockoB** [comment] 2019-08-27 10:35
Good luck @mke-tb, it will be great UX improvement for tb.

**Comment by mke-tb** [comment] 2019-09-01 12:45
I've put a couple of hours investigating this issue and here's what I came across:
- During the development of our new theme, `niara`, the JS functionality which replaces `src` attributes of the images were removed (https://github.com/thirtybees/niara/commit/bf7d101d87078f56f5d05fc7de33dacdf835d97b#diff-206bb8e5b8584223b92afae06825d2fa)
- With TB `v1.1.0`, it looks like we can say the correct URLs are assigned to the images when high-res images config is ON.
- There's another issue with this functionality, we don't regenerate existing images for 2x so when this config changes, old images won't be in high-res but that's a different topic.

The problematic part looks like the way we rewrite URLs. I assigned two different images (visually different) to 1x and 2x versions of an image and 2x URL still displayed the 1x image.

Check these two URLs for instance, they are from our demo shop:
1. https://front.thirtybees.com/3-home_default/soap.jpg
2. https://front.thirtybees.com/3-home_default/soap2x.jpg

The unwritten versions of these URLs are:
3. https://front.thirtybees.com/img/p/3/3-home_default.jpg
4. https://front.thirtybees.com/img/p/3/3-home_default2x.jpg

If you check these URLs, you would notice that there's no image for URL # 4 but # 2 still works because it simply returns the same file for 1x and 2x which is `3-home_default.jpg`.

I checked `htaccess` to see what can be done with `RewriteCond`s, specifically this line:
`RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3.jpg [L]`

As it can be seen in here, our rewriting rule doesn't care about the last part of the URL, whether `soap.jpg` or `soap2x.jpg`, it uses only the directory name for the rewrite.

To explain this better, let's split the URL based on the rule:
Image path that users see: `3-home_default/soap2x.jpg`
Regex for the RewriteRule: `^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$`

Exploded into variables using the regex:
- `$1` is `3` that matches `([0-9])`
- `$2` is `-home_default` that matches `(\-[_a-zA-Z0-9-]*)`
- `$3` is empty since no string matches `(-[0-9]+)`
When we implode these variables into `$1/$1$2$3.jpg`, it is `3-home_default`.jpg, that's why we never get the `2x` image.

**Comment by mke-tb** [comment] 2019-09-01 15:01
Ok, updated the regex to use `2x` suffix when available.

Long story short, here is an example from the old and new regexes:

Old (spaces are for easier differentiating):
```
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/    .+    \.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3  .jpg [L]
```
New:
```
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/(.+?)(2x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3$5.jpg [L]
```

**Comment by Traumflug** [comment] 2019-09-02 11:56
Great!

Sure about this `(.+?)` ? `.` means "any character", `+` means "one or more of them", and `?` ?

**Comment by mke-tb** [comment] 2019-09-02 17:23
> Great!
> 
> Sure about this `(.+?)` ? `.` means "any character", `+` means "one or more of them", and `?` ?

Well `.+` is what we already had there anyway but if we don't mark it as optional using `?`, it captures the whole file name with `2x` suffix which is not what we need. By doing `(.+?)(2x)?` we ensure that we capture `2x` separately.

**Comment by Traumflug** [comment] 2019-09-02 18:43
Sounds like `(.+?)` is equivalent to `(.*)`, then. Also, sections not needed later AFAIK need no parenthesis', so old => new would be like
```
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+     \.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3  .jpg [L]
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.*(2x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3$4.jpg [L]
```

**Comment by mke-tb** [comment] 2019-09-02 19:18
No, it's not the same. When it's `.*`, it captures it as a whole so it contains `2x`. Also we need parentheses to capture it separately.  See the attached images, I think they are more descriptive.

Without `?`:
<img width="334" alt="regex1" src="https://user-images.githubusercontent.com/54238454/64131115-d1e25300-cdc6-11e9-9bcb-94da2fecfaee.png">

Without `?` but `.*` is captured as a group:
<img width="331" alt="regex3" src="https://user-images.githubusercontent.com/54238454/64131142-00f8c480-cdc7-11e9-99b7-a99949bd2eeb.png">

With `?`:
<img width="336" alt="regex2" src="https://user-images.githubusercontent.com/54238454/64131117-d73f9d80-cdc6-11e9-8d05-436ae4f98cef.png">

**Comment by Traumflug** [comment] 2019-09-02 20:17
Obviously. Looking this up I found a question mark in this position to have a different meaning than "zero or one occurrences" ("quantifier" = `*`, `+`, ...):

> By default, the quantifiers are "greedy", that is, they match as much as possible (up to the maximum number of permitted times), without causing the rest of the pattern to fail. [...]
>
> However, if a quantifier is followed by a question mark, it ceases to be greedy, and instead matches the minimum number of times possible [...]
https://pcre.org/original/doc/html/pcrepattern.html#SEC17

Excellent, something learned, the question mark is indeed needed.

But parenthesis' not ([this evaluator](https://regex101.com/)):

![Bildschirmfoto vom 2019-09-02 um 21 57 23](https://user-images.githubusercontent.com/318581/64132043-e7f31200-cdcc-11e9-8150-5d88c4a92845.png)
![Bildschirmfoto vom 2019-09-02 um 22 03 12](https://user-images.githubusercontent.com/318581/64132113-7ff0fb80-cdcd-11e9-975b-7b96e14bf61b.png)

And surprise, surprise (to me at least), extending this to even more kinds of high-res images reduces the number of required evaluation steps even further:

![Bildschirmfoto vom 2019-09-02 um 22 07 15](https://user-images.githubusercontent.com/318581/64132163-11f90400-cdce-11e9-9010-0bcb483912c9.png)

**Comment by mke-tb** [comment] 2019-09-02 21:15
Awesome, it's a lot better now.

**Comment by MockoB** [comment] 2019-09-05 11:29
@mke-tb did you actually try if that fix is working? I added the above code in the .htaccess file of test store, where the x2 images are available and they are not called neither on my iPhone, iPad or computer. Is there any live site I could test your solution, because it's maybe me making something wrong?

**Comment by mke-tb** [comment] 2019-09-05 20:13
@MockoB Yes, I tested it by assigning visually different images for each version and the outputs were correct. Can you share the part for image overrides from your `.htaccess`?

**Comment by MockoB** [comment] 2019-09-09 14:58
Sure @mke-tb, here are the lines:

RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?(2x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3.jpg [L]

RewriteRule ^([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?(2x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$1$2$3$4.jpg [L]

RewriteRule ^([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?(2x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$1$2$3$4$5.jpg [L]

RewriteRule ^([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?(2x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg [L]

RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?(2x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg [L]

RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?(2x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg [L]

RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?(2x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg [L]

RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?(2x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg [L]

RewriteRule ^c/([0-9]+)(\-[\.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+?(2x)?\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2$3.jpg [L]

RewriteRule ^c/([a-zA-Z_-]+)(-[0-9]+)?/.+?(2x)?\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2.jpg [L]

**Comment by mke-tb** [comment] 2019-09-10 18:43
Hey @MockoB, I tested once again and it works as expected.

Can you paste the lines below by changing `myshop.com` to your address and to your `.htaccess` after `RewriteRule ^api...` and before `# Dispatcher`?

```
# Images
RewriteCond %{HTTP_HOST} ^myshop.com$
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3$4.jpg [L]
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.webp %{ENV:REWRITEBASE}img/p/$1/$1$2$3$4.webp [L]
RewriteCond %{HTTP_HOST} ^myshop.com$
RewriteRule ^([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$1$2$3$4$5.jpg [L]
RewriteRule ^([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.webp %{ENV:REWRITEBASE}img/p/$1/$2/$1$2$3$4$5.webp [L]
RewriteCond %{HTTP_HOST} ^myshop.com$
RewriteRule ^([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$1$2$3$4$5$6.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.webp %{ENV:REWRITEBASE}img/p/$1/$2/$3/$1$2$3$4$5$6.webp [L]
RewriteCond %{HTTP_HOST} ^myshop.com$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$1$2$3$4$5$6$7.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.webp %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$1$2$3$4$5$6$7.webp [L]
RewriteCond %{HTTP_HOST} ^myshop.com$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7$8.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.webp %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7$8.webp [L]
RewriteCond %{HTTP_HOST} ^myshop.com$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8$9.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.webp %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8$9.webp [L]
RewriteCond %{HTTP_HOST} ^myshop.com$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9$10.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.webp %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9$10.webp [L]
RewriteCond %{HTTP_HOST} ^myshop.com$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10$11.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.webp %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10$11.webp [L]
RewriteCond %{HTTP_HOST} ^myshop.com$
RewriteRule ^c/([0-9]+)(\-[\.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+?([2-4]x)?\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2$3$4.jpg [L]
RewriteRule ^c/([0-9]+)(\-[\.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+?([2-4]x)?\.webp %{ENV:REWRITEBASE}img/c/$1$2$3$4.webp [L]
RewriteCond %{HTTP_HOST} ^myshop.com$
RewriteRule ^c/([a-zA-Z_-]+)(-[0-9]+)?/.+?([2-4]x)?\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2$3.jpg [L]
RewriteRule ^c/([a-zA-Z_-]+)(-[0-9]+)?/.+?([2-4]x)?\.webp %{ENV:REWRITEBASE}img/c/$1$2$3.webp [L]
# AlphaImageLoader for IE and fancybox
RewriteRule ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 [L]
```

This is a file generated after I update my test shop to `issue-129` branch with CoreUpdater.

**Comment by MockoB** [comment] 2019-09-11 15:03
Ok @mke-tb,
I tried to paste the above lines in my htaccess file and replaced the domain name. Nothing changed.
Then I installed thirtybees 1.1.0 and updated to the latest version with the issue you mentioned above. Nothing changed. 
Cleared browsers cache, cleared thirtybees cache, regenerated the htaccess file, checked if the code is updated (it was). Nothing changed. 
Tried it on prestashop installation 1.7.6.0. Same thing. 

I checked with developer tools on Chrome and I can see it loads the default image on my pc with 2560/1440 resolution.

I don't know why but it took me ages to load the store on my iphone, maybe something affiliated with the changes of htaccess file. But once I opened the site the default images are still loaded (i cleared safari and chrome caches also) and no x2 images.

I can't find my ipad right now, but I'm pretty sure there will be no difference.

If you could send me link on my email of your site, so I could check it, it would be nice. My email is vassilmoskov@gmail.com, I may send you the link of my test shop also, if you are interested.

**Comment by Traumflug** [comment] 2019-09-19 12:20
>    ```
>    RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3$4.jpg [L]
>    RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+?([2-4]x)?\.webp %{ENV:REWRITEBASE}img/p/$1/$1$2$3$4.webp [L]
>    ```
There's a `$` missing after `webp`.

**Comment by MockoB** [comment] 2019-09-19 13:00
@Traumflug that's the way the file is generated in tb.
Just to mention here, that the x2 images don't work for me on @mke-tb's site, he shared with me.

**Comment by Traumflug** [comment] 2019-09-19 14:04
Well, then this file generation needs a fix :-)

**Comment by Traumflug** [comment] 2019-10-18 13:49
Moved all the commits from branch _issue-129_ to _1.1.x_. Thanks for all the work, everybody.

If there's something left, please don't hesitate to open a new issue (this already got a bit long).

**Closed by Traumflug** 2019-10-18 13:49 UTC
Labels: Bug
