### ISSUE TITLE
Tax line doesn't display in cart summary after adding info for a taxable area user

### ISSUE THREAD

**Issue by x97wehner** [thirtybees/thirtybees#657] opened 2018-11-01 21:02 UTC
when providing info in guest one page checkout, if provide a taxable area in address, on save the total price updates correctly but the tax line doesn't display until the page is manually refreshed. Should display on recalculate.
![no tax line](https://user-images.githubusercontent.com/44684415/47879801-e85efd00-ddf7-11e8-8c2a-ec1c5cf13e79.jpg)

**Comment by Traumflug** [comment] 2019-02-14 12:20
This looks like a duplicate of issue #570.

**Closed by Traumflug** 2019-02-14 12:20 UTC
