### ISSUE TITLE
Localization package does not translate menu tabs

### ISSUE THREAD

**Issue by firstred** [thirtybees/thirtybees#117] opened 2017-02-22 20:34 UTC

**Comment by Dh42** [comment] 2019-03-15 16:33
These do not translate from language to language, https://i.imgur.com/HunmE0h.png

**Comment by Traumflug** [comment] 2019-03-18 22:27
Looked into this a bit closer. Name of this menu entry isn't a global translation, but a multi-lang text field in the database. Which means the problem essentially is that adding a language doesn't update such multi-lang text fields.

A feature which AFAIK doesn't exist. Translated names right after installation get installed by the installer and come with `install-dev/langs/<lang>/data/quick_access.xml`. It isn't part of the translation system.

This raises the question whether there are worthwhile usages of having default data for multi-lang text fields other than these few names. We'd need a general solution, then.

Anyways it's an enhancement, not a bug, so marking it as this for the time being.

**Closed** 2019-05-06 16:46 UTC
Labels: Enhancement
