### ISSUE TITLE
Allow 301 redirect to category from product

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#567] opened 2018-08-11 18:02 UTC
When you deactivate a product, you can set up a 301 redirection in the backoffice. Unfortunately it's only possible to set up a redirection to another product. I believe, that a redirection to a category should be possible as well.

What do you think?

**Comment by zapps12** [comment] 2018-08-11 19:03
I think it's a great idea.
I mean, obviously you can always redirect in htaccess but it's a bit of a pain compared to changing a selection box. Had the same thought myself in the past. Wasn't sure why prestashop made it that way, but programmers don't always know much about SEO.

**Comment by doclucas** [comment] 2018-08-14 19:54
Great idea indeed

**Comment by therampagerado** [comment] 2023-02-24 15:22
@getdatakick - I saw you started scrubbing old issues so I may help if I stumble on something.

Duplicate of https://github.com/thirtybees/thirtybees/issues/1591 (there are more items in 1591)

**Comment by getdatakick** [comment] 2023-02-24 15:29
Closing as duplicate. Thanks @therampagerado

**Closed by getdatakick** 2023-02-24 15:29 UTC
Labels: Duplicate, Enhancement
