### ISSUE TITLE
Multistore enabled today - unable to set default combination on product

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1701] opened 2023-07-17 18:02 UTC
This appears to happen only when the default combination get deleted. But it worked for sure (not sure if multistore is to be blamed, probably not)

Same happens when you use the combination generator - let's say I have shoes, I remove all the combinations and then put the new availability from the left menu - the system says '×Duplicate entry '137-1' for key 'product_default''
![image](https://github.com/thirtybees/thirtybees/assets/11251370/e36b71b2-e856-403f-977e-e4fe65289ed6)

and 

![image](https://github.com/thirtybees/thirtybees/assets/11251370/49dbbb34-1ae5-407a-ac31-1c3149c86f71)

![image](https://github.com/thirtybees/thirtybees/assets/11251370/a5d56989-50c2-4e7a-b131-6d7c437786aa)

**Comment by getdatakick** [comment] 2023-07-18 06:02
Indeed, this is multi store issue.

### Reprosteps:
1) Enable multi-store and create second shop
2) Edit product in single-store context
3) Delete combination that is marked as Default

`select id_shop, id_product_attribute, default_on from tb_product_attribute_shop where id_product = 5;`

![image](https://github.com/thirtybees/thirtybees/assets/34651851/298d6247-d6ec-4cd2-97d5-ee3edf12d2e2)

`select * from tb_product_attribute where id_product = 5;`

![image](https://github.com/thirtybees/thirtybees/assets/34651851/b3765d60-addb-4a86-8b50-bb66500f0471)

4) Mark some combination as default

**Expected result**: combination should be marked as default
**Actual result**: SQL exception

Relevant code: `Product::checkDefaultAttributes`
https://github.com/thirtybees/thirtybees/blob/4d9d14f7c55ca368024d7b898508e1b2c77f4ac0/classes/Product.php#L6105-L6155

**Comment by therampagerado** [comment] 2023-07-18 08:56
Hello, @getdatakick ,

Unfortunately the issue is still present with exactly the same behavior but different error line:

- if I delete the default combination I'm unable to make a new one.
- if the default combination is there there's no issue changing it.
- if I use the combinations generator and delete all combinations i'm unable to recreate new ones, because during the process a default one is set.

![image](https://github.com/thirtybees/thirtybees/assets/11251370/f7a65ca7-29da-4762-9d8d-391db90d800a)

Thank you!

**Comment by getdatakick** [comment] 2023-07-18 09:23
I can't reproduce this.

Can you provide step-by-step, ideally on fresh installation of thirty bees/

**Comment by therampagerado** [comment] 2023-07-18 09:33
When I select "All shops" I'm able to manipulate everything and it is working as expected.

![image](https://github.com/thirtybees/thirtybees/assets/11251370/793b680e-17e7-4d40-8d3b-c64fc5b4a6da)


If I select the first of the shops, the one that was the only shop in this Multistore it is working the same way.

If I select the second shop I created yesterday it is showing different combinations and it is not allowing me to adjust them (I deleted them through combination generator):

![image](https://github.com/thirtybees/thirtybees/assets/11251370/b89648e9-94e7-436a-9834-589e2eb1f79e)

If we need to adjust those for all shops we should edit them under "all shops"?

**Comment by therampagerado** [comment] 2023-07-18 09:45
At this point I believe this is not a bug but an idiot behind the keyboard :)

I need same quantities in all shops so adjusting them per shop is wrong. I simply have to edit all shared products in All shops context.

**Closed** 2023-07-18 09:49 UTC
Labels: Bug

**Comment by getdatakick** [comment] 2023-07-18 09:50
There was indeed a bug in combination generator. Fixed by commit 2625e403506f1ed7af87697a762f06d5edef4436

**Comment by therampagerado** [comment] 2023-07-18 09:53
Thank you will update and check it. Haven't been using Mutlishop since PS1.6 and I'm little bit rusty. :)
